EXIF library (libexif) Internals: libexif/canon/exif-mnote-data-canon.c File Reference
exif-mnote-data-canon.c File Reference
#include <config.h>
#include "exif-mnote-data-canon.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <libexif/exif-byte-order.h>
#include <libexif/exif-utils.h>
#include <libexif/exif-data.h>
Macros
#define DEBUG
Functions
static void exif_mnote_data_canon_clear (ExifMnoteDataCanon *n)
static void exif_mnote_data_canon_free (ExifMnoteData *n)
static void exif_mnote_data_canon_get_tags (ExifMnoteDataCanon *dc, unsigned int n, unsigned int *m, unsigned int *s)
static char * exif_mnote_data_canon_get_value (ExifMnoteData *note, unsigned int n, char *val, unsigned int maxlen)
static void exif_mnote_data_canon_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
static void exif_mnote_data_canon_set_offset (ExifMnoteData *n, unsigned int o)
static void exif_mnote_data_canon_save (ExifMnoteData *ne, unsigned char **buf, unsigned int *buf_size)
static void exif_mnote_data_canon_load (ExifMnoteData *ne, const unsigned char *buf, unsigned int buf_size)
static unsigned int exif_mnote_data_canon_count (ExifMnoteData *n)
static unsigned int exif_mnote_data_canon_get_id (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_canon_get_name (ExifMnoteData *note, unsigned int i)
static const char * exif_mnote_data_canon_get_title (ExifMnoteData *note, unsigned int i)
static const char * exif_mnote_data_canon_get_description (ExifMnoteData *note, unsigned int i)
ExifMnoteData * exif_mnote_data_canon_new (ExifMem *mem, ExifDataOption o)
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 33 of file exif-mnote-data-canon.c.
Function Documentation
exif_mnote_data_canon_clear()
static void exif_mnote_data_canon_clear (ExifMnoteDataCanon * n) static
Definition at line 36 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_canon_free(), and exif_mnote_data_canon_load().
exif_mnote_data_canon_count()
static unsigned int exif_mnote_data_canon_count (ExifMnoteData * n) static
Definition at line 229 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, and mnote_canon_entry_count_values().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_free()
static void exif_mnote_data_canon_free (ExifMnoteData * n) static
Definition at line 56 of file exif-mnote-data-canon.c.
References exif_mnote_data_canon_clear().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_description()
static const char* exif_mnote_data_canon_get_description (ExifMnoteData * note, unsigned int i) static
Definition at line 276 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_description(), and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_id()
static unsigned int exif_mnote_data_canon_get_id (ExifMnoteData * d, unsigned int i) static
Definition at line 240 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_name()
static const char* exif_mnote_data_canon_get_name (ExifMnoteData * note, unsigned int i) static
Definition at line 252 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_name_sub(), _ExifMnoteDataCanon::options, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_tags()
static void exif_mnote_data_canon_get_tags (ExifMnoteDataCanon * dc, unsigned int n, unsigned int * m, unsigned int * s) static
Definition at line 64 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, and mnote_canon_entry_count_values().
Referenced by exif_mnote_data_canon_get_description(), exif_mnote_data_canon_get_id(), exif_mnote_data_canon_get_name(), exif_mnote_data_canon_get_title(), and exif_mnote_data_canon_get_value().
exif_mnote_data_canon_get_title()
static const char* exif_mnote_data_canon_get_title (ExifMnoteData * note, unsigned int i) static
Definition at line 264 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), mnote_canon_tag_get_title_sub(), _ExifMnoteDataCanon::options, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_get_value()
static char* exif_mnote_data_canon_get_value (ExifMnoteData * note, unsigned int n, char * val, unsigned int maxlen) static
Definition at line 81 of file exif-mnote-data-canon.c.
References _ExifMnoteDataCanon::count, _ExifMnoteDataCanon::entries, exif_mnote_data_canon_get_tags(), and mnote_canon_entry_get_value().
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_load()
static void exif_mnote_data_canon_load (ExifMnoteData * ne, const unsigned char * buf, unsigned int buf_size) static
Definition at line 183 of file exif-mnote-data-canon.c.
References _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_mem_alloc(), exif_mem_realloc(), exif_mnote_data_canon_clear(), _MnoteCanonEntry::format, _ExifMnoteData::mem, _ExifMnoteDataCanon::offset, _ExifMnoteDataCanon::order, _MnoteCanonEntry::order, _MnoteCanonEntry::size, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_new()
ExifMnoteData* exif_mnote_data_canon_new (ExifMem * mem, ExifDataOption o)
Definition at line 288 of file exif-mnote-data-canon.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_canon_count(), exif_mnote_data_canon_free(), exif_mnote_data_canon_get_description(), exif_mnote_data_canon_get_id(), exif_mnote_data_canon_get_name(), exif_mnote_data_canon_get_title(), exif_mnote_data_canon_get_value(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_canon_set_offset(), exif_mnote_data_construct(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataCanon::options, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by exif_data_load_data().
exif_mnote_data_canon_save()
static void exif_mnote_data_canon_save (ExifMnoteData * ne, unsigned char ** buf, unsigned int * buf_size) static
Definition at line 117 of file exif-mnote-data-canon.c.
References _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_format_get_size(), exif_mem_alloc(), exif_mem_realloc(), exif_set_long(), exif_set_short(), _MnoteCanonEntry::format, _ExifMnoteData::mem, _ExifMnoteDataCanon::offset, _ExifMnoteDataCanon::order, and _MnoteCanonEntry::tag.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_set_byte_order()
static void exif_mnote_data_canon_set_byte_order (ExifMnoteData * d, ExifByteOrder o) static
Definition at line 93 of file exif-mnote-data-canon.c.
References _MnoteCanonEntry::components, _ExifMnoteDataCanon::count, _MnoteCanonEntry::data, _ExifMnoteDataCanon::entries, exif_array_set_byte_order(), _MnoteCanonEntry::format, _ExifMnoteDataCanon::order, and _MnoteCanonEntry::order.
Referenced by exif_mnote_data_canon_new().
exif_mnote_data_canon_set_offset()
static void exif_mnote_data_canon_set_offset (ExifMnoteData * n, unsigned int o) static
Definition at line 111 of file exif-mnote-data-canon.c.
Referenced by exif_mnote_data_canon_new().