EXIF library (libexif) Internals: libexif/exif-utils.c File Reference
exif-utils.c File Reference
#include <config.h>
#include <libexif/exif-utils.h>
Functions
void exif_array_set_byte_order (ExifFormat f, unsigned char *b, unsigned int n, ExifByteOrder o_orig, ExifByteOrder o_new)
ExifSShort exif_get_sshort (const unsigned char *buf, ExifByteOrder order)
ExifShort exif_get_short (const unsigned char *buf, ExifByteOrder order)
void exif_set_sshort (unsigned char *b, ExifByteOrder order, ExifSShort value)
void exif_set_short (unsigned char *b, ExifByteOrder order, ExifShort value)
ExifSLong exif_get_slong (const unsigned char *b, ExifByteOrder order)
void exif_set_slong (unsigned char *b, ExifByteOrder order, ExifSLong value)
ExifLong exif_get_long (const unsigned char *buf, ExifByteOrder order)
void exif_set_long (unsigned char *b, ExifByteOrder order, ExifLong value)
ExifSRational exif_get_srational (const unsigned char *buf, ExifByteOrder order)
ExifRational exif_get_rational (const unsigned char *buf, ExifByteOrder order)
void exif_set_rational (unsigned char *buf, ExifByteOrder order, ExifRational value)
void exif_set_srational (unsigned char *buf, ExifByteOrder order, ExifSRational value)
Function Documentation
exif_array_set_byte_order()
void exif_array_set_byte_order (ExifFormat f, unsigned char * b, unsigned int n, ExifByteOrder o_orig, ExifByteOrder o_new)
Definition at line 26 of file exif-utils.c.
References EXIF_FORMAT_ASCII, EXIF_FORMAT_BYTE, exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), exif_get_sshort(), exif_set_long(), exif_set_rational(), exif_set_short(), exif_set_slong(), exif_set_srational(), and exif_set_sshort().
Referenced by entry_set_byte_order(), exif_mnote_data_canon_set_byte_order(), exif_mnote_data_olympus_set_byte_order(), and exif_mnote_data_pentax_set_byte_order().
exif_get_long()
ExifLong exif_get_long (const unsigned char * buf, ExifByteOrder order)
Definition at line 165 of file exif-utils.c.
References exif_get_slong().
Referenced by exif_array_set_byte_order(), exif_data_load_data(), exif_data_load_data_content(), exif_data_load_data_entry(), exif_entry_fix(), exif_entry_get_value(), exif_get_rational(), exif_mnote_data_canon_load(), exif_mnote_data_olympus_load(), exif_mnote_data_pentax_load(), mnote_canon_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_get_rational()
ExifRational exif_get_rational (const unsigned char * buf, ExifByteOrder order)
Definition at line 188 of file exif-utils.c.
References ExifRational::denominator, exif_get_long(), and ExifRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_get_value(), and mnote_olympus_entry_get_value().
exif_get_short()
ExifShort exif_get_short (const unsigned char * buf, ExifByteOrder order)
Definition at line 102 of file exif-utils.c.
References exif_get_sshort().
Referenced by cmp_func(), exif_array_set_byte_order(), exif_data_load_data(), exif_data_load_data_content(), exif_data_load_data_entry(), exif_entry_get_value(), exif_mnote_data_canon_load(), exif_mnote_data_olympus_load(), exif_mnote_data_pentax_load(), mnote_canon_entry_count_values(), mnote_canon_entry_get_value(), mnote_olympus_entry_get_value(), and mnote_pentax_entry_get_value().
exif_get_slong()
ExifSLong exif_get_slong (const unsigned char * b, ExifByteOrder order)
Definition at line 130 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), exif_entry_get_value(), exif_get_long(), and exif_get_srational().
exif_get_srational()
ExifSRational exif_get_srational (const unsigned char * buf, ExifByteOrder order)
Definition at line 177 of file exif-utils.c.
References ExifSRational::denominator, exif_get_slong(), and ExifSRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), and exif_entry_get_value().
exif_get_sshort()
ExifSShort exif_get_sshort (const unsigned char * buf, ExifByteOrder order)
Definition at line 87 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), and exif_get_short().
exif_set_long()
void exif_set_long (unsigned char * b, ExifByteOrder order, ExifLong value)
Definition at line 171 of file exif-utils.c.
References exif_set_slong().
Referenced by exif_array_set_byte_order(), exif_data_save_data(), exif_data_save_data_content(), exif_data_save_data_entry(), exif_mnote_data_canon_save(), exif_mnote_data_olympus_save(), and exif_set_rational().
exif_set_rational()
void exif_set_rational (unsigned char * buf, ExifByteOrder order, ExifRational value)
Definition at line 199 of file exif-utils.c.
References ExifRational::denominator, exif_set_long(), and ExifRational::numerator.
Referenced by exif_array_set_byte_order(), exif_entry_fix(), and exif_entry_initialize().
exif_set_short()
void exif_set_short (unsigned char * b, ExifByteOrder order, ExifShort value)
Definition at line 124 of file exif-utils.c.
References exif_set_sshort().
Referenced by exif_array_set_byte_order(), exif_data_save_data(), exif_data_save_data_content(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_initialize(), exif_mnote_data_canon_save(), and exif_mnote_data_olympus_save().
exif_set_slong()
void exif_set_slong (unsigned char * b, ExifByteOrder order, ExifSLong value)
Definition at line 145 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), exif_set_long(), and exif_set_srational().
exif_set_srational()
void exif_set_srational (unsigned char * buf, ExifByteOrder order, ExifSRational value)
Definition at line 208 of file exif-utils.c.
References ExifSRational::denominator, exif_set_slong(), and ExifSRational::numerator.
Referenced by exif_array_set_byte_order().
exif_set_sshort()
void exif_set_sshort (unsigned char * b, ExifByteOrder order, ExifSShort value)
Definition at line 108 of file exif-utils.c.
References EXIF_BYTE_ORDER_INTEL, and EXIF_BYTE_ORDER_MOTOROLA.
Referenced by exif_array_set_byte_order(), and exif_set_short().