EXIF library (libexif) Internals: libexif/exif-data.h File Reference
exif-data.h File Reference
FIXME foo bar blah.
#include <libexif/exif-byte-order.h>
#include <libexif/exif-data-type.h>
#include <libexif/exif-ifd.h>
#include <libexif/exif-log.h>
#include <libexif/exif-tag.h>
#include <libexif/exif-content.h>
#include <libexif/exif-mnote-data.h>
#include <libexif/exif-mem.h>
Data Structures
struct _ExifData
Macros
#define exif_data_get_entry(d, t)
Typedefs
typedef struct _ExifData ExifData
typedef struct _ExifDataPrivate ExifDataPrivate
typedef void(* ExifDataForeachContentFunc) (ExifContent *, void *user_data)
Enumerations
enum ExifDataOption { EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS = 1 << 0 , EXIF_DATA_OPTION_FOLLOW_SPECIFICATION = 1 << 1 , EXIF_DATA_OPTION_DONT_CHANGE_MAKER_NOTE = 1 << 2 }
Functions
ExifData * exif_data_new (void)
ExifData * exif_data_new_mem (ExifMem *)
ExifData * exif_data_new_from_file (const char *path)
load exif data from file
ExifData * exif_data_new_from_data (const unsigned char *data, unsigned int size)
void exif_data_load_data (ExifData *data, const unsigned char *d, unsigned int size)
void exif_data_save_data (ExifData *data, unsigned char **d, unsigned int *size)
void exif_data_ref (ExifData *data)
void exif_data_unref (ExifData *data)
void exif_data_free (ExifData *data)
ExifByteOrder exif_data_get_byte_order (ExifData *data)
void exif_data_set_byte_order (ExifData *data, ExifByteOrder order)
ExifMnoteData * exif_data_get_mnote_data (ExifData *)
void exif_data_fix (ExifData *)
void exif_data_foreach_content (ExifData *data, ExifDataForeachContentFunc func, void *user_data)
const char * exif_data_option_get_name (ExifDataOption)
const char * exif_data_option_get_description (ExifDataOption)
void exif_data_set_option (ExifData *, ExifDataOption)
void exif_data_unset_option (ExifData *, ExifDataOption)
void exif_data_set_data_type (ExifData *, ExifDataType)
ExifDataType exif_data_get_data_type (ExifData *)
void exif_data_dump (ExifData *data)
void exif_data_log (ExifData *data, ExifLog *log)
Detailed Description
FIXME foo bar blah.
Author
Lutz Müller lutz@.nosp@m.user.nosp@m.s.sou.nosp@m.rcef.nosp@m.orge..nosp@m.net
Date
2001-2005
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
Definition in file exif-data.h.
Macro Definition Documentation
exif_data_get_entry
#define exif_data_get_entry (d, t)
Value:
        (exif_content_get_entry(d->ifd[EXIF_IFD_0],t) ?                 \
         exif_content_get_entry(d->ifd[EXIF_IFD_0],t) :                 \
         exif_content_get_entry(d->ifd[EXIF_IFD_1],t) ?                 \
         exif_content_get_entry(d->ifd[EXIF_IFD_1],t) :                 \
         exif_content_get_entry(d->ifd[EXIF_IFD_EXIF],t) ?              \
         exif_content_get_entry(d->ifd[EXIF_IFD_EXIF],t) :              \
         exif_content_get_entry(d->ifd[EXIF_IFD_GPS],t) ?               \
         exif_content_get_entry(d->ifd[EXIF_IFD_GPS],t) :               \
         exif_content_get_entry(d->ifd[EXIF_IFD_INTEROPERABILITY],t) ?  \
         exif_content_get_entry(d->ifd[EXIF_IFD_INTEROPERABILITY],t) : NULL)
Definition at line 104 of file exif-data.h.
Typedef Documentation
ExifData
typedef struct _ExifData ExifData
Definition at line 1 of file exif-data.h.
ExifDataForeachContentFunc
typedef void(* ExifDataForeachContentFunc) (ExifContent *, void *user_data)
Definition at line 80 of file exif-data.h.
ExifDataPrivate
typedef struct _ExifDataPrivate ExifDataPrivate
Definition at line 1 of file exif-data.h.
Enumeration Type Documentation
ExifDataOption
enum ExifDataOption
Enumerator
EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS
EXIF_DATA_OPTION_FOLLOW_SPECIFICATION
EXIF_DATA_OPTION_DONT_CHANGE_MAKER_NOTE
Definition at line 85 of file exif-data.h.
Function Documentation
exif_data_dump()
void exif_data_dump (ExifData * data)
Definition at line 986 of file exif-data.c.
References _ExifContent::count, _ExifData::data, exif_content_dump(), EXIF_IFD_COUNT, exif_ifd_get_name(), _ExifData::ifd, and _ExifData::size.
exif_data_fix()
void exif_data_fix (ExifData * d)
Definition at line 1174 of file exif-data.c.
References exif_data_foreach_content(), and fix_func().
Referenced by exif_data_load_data().
exif_data_foreach_content()
void exif_data_foreach_content (ExifData * data, ExifDataForeachContentFunc func, void * user_data)
Definition at line 1022 of file exif-data.c.
Referenced by exif_data_fix(), and exif_data_set_byte_order().
exif_data_free()
void exif_data_free (ExifData * data)
Definition at line 949 of file exif-data.c.
References _ExifData::data, exif_content_unref(), EXIF_IFD_COUNT, exif_log_unref(), exif_mem_free(), exif_mem_unref(), exif_mnote_data_unref(), _ExifData::ifd, _ExifDataPrivate::log, _ExifDataPrivate::md, _ExifDataPrivate::mem, and _ExifData::priv.
Referenced by exif_data_new_mem(), and exif_data_unref().
exif_data_get_byte_order()
ExifByteOrder exif_data_get_byte_order (ExifData * data)
Definition at line 1013 of file exif-data.c.
References _ExifDataPrivate::order, and _ExifData::priv.
Referenced by exif_entry_fix(), exif_entry_get_value(), and exif_entry_initialize().
exif_data_get_data_type()
ExifDataType exif_data_get_data_type (ExifData * d)
Definition at line 1189 of file exif-data.c.
References _ExifDataPrivate::data_type, EXIF_DATA_TYPE_COUNT, and _ExifData::priv.
Referenced by exif_content_fix().
exif_data_get_mnote_data()
ExifMnoteData* exif_data_get_mnote_data (ExifData * d)
Definition at line 88 of file exif-data.c.
References _ExifDataPrivate::md, and _ExifData::priv.
exif_data_load_data()
void exif_data_load_data (ExifData * data, const unsigned char * d, unsigned int size)
Definition at line 698 of file exif-data.c.
References _, EXIF_BYTE_ORDER_INTEL, EXIF_BYTE_ORDER_MOTOROLA, exif_data_fix(), exif_data_get_type_maker_note(), exif_data_load_data_content(), EXIF_DATA_OPTION_FOLLOW_SPECIFICATION, EXIF_DATA_TYPE_MAKER_NOTE_CANON, EXIF_DATA_TYPE_MAKER_NOTE_OLYMPUS, EXIF_DATA_TYPE_MAKER_NOTE_PENTAX, exif_get_long(), exif_get_short(), EXIF_IFD_0, EXIF_IFD_1, exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_CODE_DEBUG, exif_mnote_data_canon_new(), exif_mnote_data_load(), exif_mnote_data_log(), exif_mnote_data_olympus_new(), exif_mnote_data_pentax_new(), exif_mnote_data_set_byte_order(), exif_mnote_data_set_offset(), ExifHeader, JPEG_MARKER_APP0, JPEG_MARKER_APP1, JPEG_MARKER_SOI, _ExifDataPrivate::log, LOG_TOO_SMALL, _ExifDataPrivate::md, _ExifDataPrivate::mem, _ExifDataPrivate::offset_mnote, _ExifDataPrivate::options, _ExifDataPrivate::order, and _ExifData::priv.
Referenced by exif_data_new_from_data(), and exif_loader_get_data().
exif_data_log()
void exif_data_log (ExifData * data, ExifLog * log)
Definition at line 1073 of file exif-data.c.
References exif_content_log(), EXIF_IFD_COUNT, exif_log_ref(), exif_log_unref(), _ExifData::ifd, _ExifDataPrivate::log, and _ExifData::priv.
Referenced by exif_loader_get_data().
exif_data_new()
ExifData* exif_data_new (void)
Definition at line 94 of file exif-data.c.
References exif_data_new_mem(), exif_mem_new_default(), and exif_mem_unref().
Referenced by exif_data_new_from_data().
exif_data_new_from_data()
ExifData* exif_data_new_from_data (const unsigned char * data, unsigned int size)
Definition at line 146 of file exif-data.c.
References exif_data_load_data(), exif_data_new(), and size.
exif_data_new_from_file()
ExifData* exif_data_new_from_file (const char * path)
load exif data from file
Parameters
[in] path filename including path
Foo bar blah bleh baz.
Definition at line 915 of file exif-data.c.
References exif_loader_get_data(), exif_loader_new(), exif_loader_unref(), and exif_loader_write_file().
exif_data_new_mem()
ExifData* exif_data_new_mem (ExifMem * mem)
Definition at line 105 of file exif-data.c.
References exif_content_new_mem(), exif_data_free(), EXIF_DATA_OPTION_FOLLOW_SPECIFICATION, EXIF_DATA_OPTION_IGNORE_UNKNOWN_TAGS, exif_data_set_data_type(), exif_data_set_option(), EXIF_DATA_TYPE_COUNT, EXIF_IFD_COUNT, exif_mem_alloc(), exif_mem_free(), exif_mem_ref(), _ExifData::ifd, _ExifDataPrivate::mem, _ExifContent::parent, _ExifData::priv, and _ExifDataPrivate::ref_count.
Referenced by exif_data_new(), and exif_loader_get_data().
exif_data_option_get_description()
const char* exif_data_option_get_description (ExifDataOption o)
Definition at line 1125 of file exif-data.c.
References _, description, exif_data_option, and option.
exif_data_option_get_name()
const char* exif_data_option_get_name (ExifDataOption o)
Definition at line 1114 of file exif-data.c.
References _, exif_data_option, name, and option.
exif_data_ref()
void exif_data_ref (ExifData * data)
Definition at line 929 of file exif-data.c.
References _ExifData::priv, and _ExifDataPrivate::ref_count.
exif_data_save_data()
void exif_data_save_data (ExifData * data, unsigned char ** d, unsigned int * size)
Definition at line 875 of file exif-data.c.
References EXIF_BYTE_ORDER_INTEL, exif_data_alloc(), exif_data_save_data_content(), EXIF_IFD_0, exif_log(), EXIF_LOG_CODE_DEBUG, exif_set_long(), exif_set_short(), ExifHeader, _ExifData::ifd, _ExifDataPrivate::log, _ExifDataPrivate::order, and _ExifData::priv.
exif_data_set_byte_order()
void exif_data_set_byte_order (ExifData * data, ExifByteOrder order)
Definition at line 1057 of file exif-data.c.
References content_set_byte_order(), exif_data_foreach_content(), exif_mnote_data_set_byte_order(), _ExifDataPrivate::md, _ByteOrderChangeData::new, _ByteOrderChangeData::old, _ExifDataPrivate::order, and _ExifData::priv.
exif_data_set_data_type()
void exif_data_set_data_type (ExifData * d, ExifDataType dt)
Definition at line 1180 of file exif-data.c.
References _ExifDataPrivate::data_type, and _ExifData::priv.
Referenced by exif_data_new_mem().
exif_data_set_option()
void exif_data_set_option (ExifData * d, ExifDataOption o)
Definition at line 1136 of file exif-data.c.
References _ExifDataPrivate::options, and _ExifData::priv.
Referenced by exif_data_new_mem().
exif_data_unref()
void exif_data_unref (ExifData * data)
Definition at line 938 of file exif-data.c.
References exif_data_free(), _ExifData::priv, and _ExifDataPrivate::ref_count.
exif_data_unset_option()
void exif_data_unset_option (ExifData * d, ExifDataOption o)
Definition at line 1145 of file exif-data.c.
References _ExifDataPrivate::options, and _ExifData::priv.