EXIF library (libexif) Internals: libexif/exif-tag.c File Reference
exif-tag.c File Reference
#include <config.h>
#include <libexif/exif-tag.h>
#include <libexif/i18n.h>
#include <stdlib.h>
#include <string.h>
Macros
#define ESL_NNNN { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
#define ESL_OOOO { EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL }
#define ESL_MMMN { EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
#define ESL_MMMM { EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY }
#define ESL_OMON { EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
#define ESL_NNOO { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL }
#define ESL_NNMN { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
#define ESL_NNMM { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY }
#define ESL_NNNM { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY }
#define ESL_NNNO { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_OPTIONAL }
#define ESL_GPS { ESL_NNNN, ESL_NNNN, ESL_NNNN, ESL_OOOO, ESL_NNNN }
#define RECORDED
Typedefs
typedef const char *(* get_stuff_func) (ExifTag tag, ExifIfd ifd)
Functions
ExifTag exif_tag_table_get_tag (unsigned int n)
const char * exif_tag_table_get_name (unsigned int n)
unsigned int exif_tag_table_count (void)
const char * exif_tag_get_name_in_ifd (ExifTag tag, ExifIfd ifd)
const char * exif_tag_get_title_in_ifd (ExifTag tag, ExifIfd ifd)
const char * exif_tag_get_description_in_ifd (ExifTag tag, ExifIfd ifd)
static const char * exif_tag_get_stuff (ExifTag tag, get_stuff_func func)
const char * exif_tag_get_name (ExifTag tag)
const char * exif_tag_get_title (ExifTag tag)
const char * exif_tag_get_description (ExifTag tag)
ExifTag exif_tag_from_name (const char *name)
ExifSupportLevel exif_tag_get_support_level_in_ifd (ExifTag tag, ExifIfd ifd, ExifDataType t)
Variables
struct {
ExifTag tag
const char * name
const char * title
const char * description
ExifSupportLevel esl [EXIF_IFD_COUNT][4]
} ExifTagTable []
Macro Definition Documentation
ESL_GPS
#define ESL_GPS { ESL_NNNN, ESL_NNNN, ESL_NNNN, ESL_OOOO, ESL_NNNN }
Definition at line 39 of file exif-tag.c.
ESL_MMMM
#define ESL_MMMM { EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY }
Definition at line 32 of file exif-tag.c.
ESL_MMMN
#define ESL_MMMN { EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
Definition at line 31 of file exif-tag.c.
ESL_NNMM
#define ESL_NNMM { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_MANDATORY }
Definition at line 36 of file exif-tag.c.
ESL_NNMN
#define ESL_NNMN { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
Definition at line 35 of file exif-tag.c.
ESL_NNNM
#define ESL_NNNM { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_MANDATORY }
Definition at line 37 of file exif-tag.c.
ESL_NNNN
#define ESL_NNNN { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
Definition at line 29 of file exif-tag.c.
ESL_NNNO
#define ESL_NNNO { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_OPTIONAL }
Definition at line 38 of file exif-tag.c.
ESL_NNOO
#define ESL_NNOO { EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL }
Definition at line 34 of file exif-tag.c.
ESL_OMON
#define ESL_OMON { EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_MANDATORY, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_NOT_RECORDED }
Definition at line 33 of file exif-tag.c.
ESL_OOOO
#define ESL_OOOO { EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL, EXIF_SUPPORT_LEVEL_OPTIONAL }
Definition at line 30 of file exif-tag.c.
RECORDED
#define RECORDED
Value:
((ExifTagTable[i].esl[ifd][EXIF_DATA_TYPE_UNCOMPRESSED_CHUNKY] != EXIF_SUPPORT_LEVEL_NOT_RECORDED) || \
 (ExifTagTable[i].esl[ifd][EXIF_DATA_TYPE_UNCOMPRESSED_PLANAR] != EXIF_SUPPORT_LEVEL_NOT_RECORDED) || \
 (ExifTagTable[i].esl[ifd][EXIF_DATA_TYPE_UNCOMPRESSED_YCC] != EXIF_SUPPORT_LEVEL_NOT_RECORDED) || \
 (ExifTagTable[i].esl[ifd][EXIF_DATA_TYPE_COMPRESSED] != EXIF_SUPPORT_LEVEL_NOT_RECORDED))
Definition at line 700 of file exif-tag.c.
Typedef Documentation
get_stuff_func
typedef const char*(* get_stuff_func) (ExifTag tag, ExifIfd ifd)
Definition at line 762 of file exif-tag.c.
Function Documentation
exif_tag_from_name()
ExifTag exif_tag_from_name (const char * name)
Definition at line 806 of file exif-tag.c.
References ExifTagTable, and name.
exif_tag_get_description()
const char* exif_tag_get_description (ExifTag tag)
Definition at line 798 of file exif-tag.c.
References exif_tag_get_description_in_ifd(), exif_tag_get_stuff(), and tag.
exif_tag_get_description_in_ifd()
const char* exif_tag_get_description_in_ifd (ExifTag tag, ExifIfd ifd)
Definition at line 738 of file exif-tag.c.
References _, bindtextdomain, description, EXIF_IFD_COUNT, ExifTagTable, ifd, RECORDED, and tag.
Referenced by exif_tag_get_description().
exif_tag_get_name()
const char* exif_tag_get_name (ExifTag tag)
Definition at line 786 of file exif-tag.c.
References exif_tag_get_name_in_ifd(), exif_tag_get_stuff(), and tag.
Referenced by exif_content_add_entry(), exif_data_load_data_entry(), exif_entry_dump(), and exif_entry_fix().
exif_tag_get_name_in_ifd()
const char* exif_tag_get_name_in_ifd (ExifTag tag, ExifIfd ifd)
Definition at line 707 of file exif-tag.c.
References EXIF_IFD_COUNT, ExifTagTable, ifd, RECORDED, and tag.
Referenced by exif_content_fix(), exif_data_load_data_content(), and exif_tag_get_name().
exif_tag_get_stuff()
static const char* exif_tag_get_stuff (ExifTag tag, get_stuff_func func) static
Definition at line 765 of file exif-tag.c.
References EXIF_IFD_0, EXIF_IFD_1, EXIF_IFD_EXIF, EXIF_IFD_GPS, EXIF_IFD_INTEROPERABILITY, and tag.
Referenced by exif_tag_get_description(), exif_tag_get_name(), and exif_tag_get_title().
exif_tag_get_support_level_in_ifd()
ExifSupportLevel exif_tag_get_support_level_in_ifd (ExifTag tag, ExifIfd ifd, ExifDataType t)
Definition at line 818 of file exif-tag.c.
References esl, EXIF_DATA_TYPE_COUNT, EXIF_IFD_COUNT, EXIF_SUPPORT_LEVEL_NOT_RECORDED, EXIF_SUPPORT_LEVEL_UNKNOWN, ExifTagTable, ifd, and tag.
Referenced by exif_content_fix().
exif_tag_get_title()
const char* exif_tag_get_title (ExifTag tag)
Definition at line 792 of file exif-tag.c.
References exif_tag_get_stuff(), exif_tag_get_title_in_ifd(), and tag.
exif_tag_get_title_in_ifd()
const char* exif_tag_get_title_in_ifd (ExifTag tag, ExifIfd ifd)
Definition at line 718 of file exif-tag.c.
References _, bindtextdomain, EXIF_IFD_COUNT, ExifTagTable, ifd, RECORDED, tag, and title.
Referenced by exif_tag_get_title().
exif_tag_table_count()
unsigned int exif_tag_table_count (void)
Definition at line 695 of file exif-tag.c.
References ExifTagTable.
Referenced by exif_tag_table_get_name(), and exif_tag_table_get_tag().
exif_tag_table_get_name()
const char * exif_tag_table_get_name (unsigned int n)
Definition at line 689 of file exif-tag.c.
References exif_tag_table_count(), and ExifTagTable.
exif_tag_table_get_tag()
ExifTag exif_tag_table_get_tag (unsigned int n)
Definition at line 683 of file exif-tag.c.
References exif_tag_table_count(), and ExifTagTable.
Variable Documentation
description
const char* description
Definition at line 45 of file exif-tag.c.
Referenced by exif_tag_get_description_in_ifd().
esl
ExifSupportLevel esl[EXIF_IFD_COUNT][4]
Definition at line 46 of file exif-tag.c.
Referenced by exif_tag_get_support_level_in_ifd().
struct { ... } ExifTagTable[]
Referenced by exif_tag_from_name(), exif_tag_get_description_in_ifd(), exif_tag_get_name_in_ifd(), exif_tag_get_support_level_in_ifd(), exif_tag_get_title_in_ifd(), exif_tag_table_count(), exif_tag_table_get_name(), and exif_tag_table_get_tag().
name
const char* name
Definition at line 43 of file exif-tag.c.
Referenced by exif_tag_from_name().
tag
ExifTag tag
Definition at line 42 of file exif-tag.c.
Referenced by exif_tag_get_description(), exif_tag_get_description_in_ifd(), exif_tag_get_name(), exif_tag_get_name_in_ifd(), exif_tag_get_stuff(), exif_tag_get_support_level_in_ifd(), exif_tag_get_title(), and exif_tag_get_title_in_ifd().
title
const char* title
Definition at line 44 of file exif-tag.c.
Referenced by exif_tag_get_title_in_ifd().