EXIF library (libexif) Internals: libexif/exif.c File Reference
exif.c File Reference
#include <sys/time.h>
#include <malloc.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/stat.h>
#include <stdarg.h>
#include <fcntl.h>
#include "exif.h"
Data Structures
struct ImageInfoType
struct Section_t
struct ExifTag
struct MakerNote
Macros
#define TRUE 1
#define FALSE 0
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define M_SOF0 0xC0 /* Start Of Frame N */
#define M_SOF1 0xC1 /* N indicates which compression process */
#define M_SOF2 0xC2 /* Only SOF0-SOF2 are now in common use */
#define M_SOF3 0xC3
#define M_SOF5 0xC5 /* NB: codes C4 and CC are NOT SOF markers */
#define M_SOF6 0xC6
#define M_SOF7 0xC7
#define M_SOF9 0xC9
#define M_SOF10 0xCA
#define M_SOF11 0xCB
#define M_SOF13 0xCD
#define M_SOF14 0xCE
#define M_SOF15 0xCF
#define M_SOI 0xD8 /* Start Of Image (beginning of datastream) */
#define M_EOI 0xD9 /* End Of Image (end of datastream) */
#define M_SOS 0xDA /* Start Of Scan (begins compressed data) */
#define M_EXIF 0xE1
#define M_COM 0xFE /* COMment */
#define PSEUDO_IMAGE_MARKER 0x123; /* Extra value. */
#define EXIF_ALLOC_SIZE 16
#define NUM_FORMATS EXIF_FMT_DOUBLE
#define TAG_EXIF_OFFSET 0x8769
#define TAG_INTEROP_OFFSET 0xa005
#define TAG_COMPRESSION 0x0103
#define TAG_MAKE 0x010F
#define TAG_MODEL 0x0110
#define TAG_ORIENTATION 0x0112
#define TAG_SOFTWARE 0x0131
#define TAG_SPECIALMODE 0x0200
#define TAG_JPEGQUAL 0x0201
#define TAG_MACRO 0x0202
#define TAG_DIGIZOOM 0x0204
#define TAG_SOFTWARERELEASE 0x0207
#define TAG_PICTINFO 0x0208
#define TAG_CAMERAID 0x0209
#define TAG_COPYRIGHT 0x8298
#define TAG_EXPOSURETIME 0x829A
#define TAG_FNUMBER 0x829D
#define TAG_GPSINFO 0x8825
#define TAG_ISOSPEED 0x8827
#define TAG_EXIFVERSION 0x9000
#define TAG_SHUTTERSPEED 0x9201
#define TAG_APERTURE 0x9202
#define TAG_MAXAPERTURE 0x9205
#define TAG_FOCALLENGTH 0x920A
#define TAG_DATETIME_ORIGINAL 0x9003
#define TAG_USERCOMMENT 0x9286
#define TAG_SUBJECT_DISTANCE 0x9206
#define TAG_LIGHT_SOURCE 0x9208
#define TAG_FLASH 0x9209
#define TAG_FOCALPLANEXRES 0xa20E
#define TAG_FOCALPLANEUNITS 0xa210
#define TAG_IMAGEWIDTH 0xA002
Typedefs
typedef unsigned char uchar
Functions
static char * exif_strndup (char *str, int len)
struct exif_data * exif_alloc (void)
static void exif_error (char *fmt,...)
static int exif_append_data (exif_data_t **d_p, char *name, char rec_type, int exif_format, exif_rec_data_t *data)
static int Get16m (void *Short)
static void process_COM (ImageInfoType *ImageInfo, uchar *Data, int length)
static void process_SOFn (ImageInfoType *ImageInfo, uchar *Data, int marker)
static int Get16u (void *Short, int MotorolaOrder)
static int Get32s (void *Long, int MotorolaOrder)
static unsigned Get32u (void *Long, int MotorolaOrder)
static double ConvertAnyFormat (void *ValuePtr, int Format, int MotorolaOrder)
static char ConvertAnyFormat2 (void *ValuePtr, int ByteCount, int Format, int MotorolaOrder, exif_rec_data_t *data_p)
static void ProcessFocalPlaneUnits (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p)
static void ProcessVersion (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p)
static void ProcessUserComment (ImageInfoType *ImageInfo, void *_ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p)
static void ProcessShutterSpeed (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p)
static void ProcessAperture (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p)
static void ProcessCanonMakerNote (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p, char *OffsetBase)
static void ProcessMakerNote (ImageInfoType *ImageInfo, void *ValuePtr, int ByteCount, int Format, struct ExifTag *tag_p, char *OffsetBase)
static int ProcessExifDir (ImageInfoType *ImageInfo, char *DirStart, char *OffsetBase, unsigned ExifLength, char *LastExifRefd)
static int process_EXIF (ImageInfoType *ImageInfo, char *CharBuf, unsigned int length, char *LastExifRefd)
static int scan_JPEG_header (ImageInfoType *ImageInfo, FILE *infile, Section_t *Sections, int *SectionsRead, int ReadAll, char *LastExifRefd)
static void DiscardData (Section_t *Sections, int *SectionsRead)
static int ReadJpegFile (ImageInfoType *ImageInfo, Section_t *Sections, int *SectionsRead, int fd, int ReadAll, char *LastExifRefd)
static int read_jpeg_exif (ImageInfoType *ImageInfo, int fd, int ReadAll)
exif_data_t * exif_parse_fd (int fd)
exif_data_t * exif_parse_file (const char *filename)
void exif_free_data (struct exif_data *d)
void exif_init (void *(*malloc_fn)(int), void(*free_fn)(void *), void *(*realloc_fn)(void *, int))
exif_record_t * exif_find_record (exif_data_t *d, const char *rec_name)
Variables
void *(* exif_malloc_fn)(int)
void *(* exif_realloc_fn)(void *, int)
void(* exif_free_fn)(void *)
static int ExifBytesPerFormat [] = {0,1,1,2,4,8,1,1,2,4,8,4,8}
static struct MakerNote MakerProcessors []
static struct ExifTag TagTable []
Macro Definition Documentation
EXIF_ALLOC_SIZE
#define EXIF_ALLOC_SIZE 16
Definition at line 129 of file exif.c.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 97 of file exif.c.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 98 of file exif.c.
FALSE
#define FALSE 0
Definition at line 42 of file exif.c.
M_COM
#define M_COM 0xFE /* COMment */
Definition at line 124 of file exif.c.
M_EOI
#define M_EOI 0xD9 /* End Of Image (end of datastream) */
Definition at line 121 of file exif.c.
M_EXIF
#define M_EXIF 0xE1
Definition at line 123 of file exif.c.
M_SOF0
#define M_SOF0 0xC0 /* Start Of Frame N */
Definition at line 107 of file exif.c.
M_SOF1
#define M_SOF1 0xC1 /* N indicates which compression process */
Definition at line 108 of file exif.c.
M_SOF10
#define M_SOF10 0xCA
Definition at line 115 of file exif.c.
M_SOF11
#define M_SOF11 0xCB
Definition at line 116 of file exif.c.
M_SOF13
#define M_SOF13 0xCD
Definition at line 117 of file exif.c.
M_SOF14
#define M_SOF14 0xCE
Definition at line 118 of file exif.c.
M_SOF15
#define M_SOF15 0xCF
Definition at line 119 of file exif.c.
M_SOF2
#define M_SOF2 0xC2 /* Only SOF0-SOF2 are now in common use */
Definition at line 109 of file exif.c.
M_SOF3
#define M_SOF3 0xC3
Definition at line 110 of file exif.c.
M_SOF5
#define M_SOF5 0xC5 /* NB: codes C4 and CC are NOT SOF markers */
Definition at line 111 of file exif.c.
M_SOF6
#define M_SOF6 0xC6
Definition at line 112 of file exif.c.
M_SOF7
#define M_SOF7 0xC7
Definition at line 113 of file exif.c.
M_SOF9
#define M_SOF9 0xC9
Definition at line 114 of file exif.c.
M_SOI
#define M_SOI 0xD8 /* Start Of Image (beginning of datastream) */
Definition at line 120 of file exif.c.
M_SOS
#define M_SOS 0xDA /* Start Of Scan (begins compressed data) */
Definition at line 122 of file exif.c.
NUM_FORMATS
#define NUM_FORMATS EXIF_FMT_DOUBLE
Definition at line 258 of file exif.c.
PSEUDO_IMAGE_MARKER
#define PSEUDO_IMAGE_MARKER 0x123; /* Extra value. */
Definition at line 127 of file exif.c.
TAG_APERTURE
#define TAG_APERTURE 0x9202
Definition at line 295 of file exif.c.
TAG_CAMERAID
#define TAG_CAMERAID 0x0209
Definition at line 282 of file exif.c.
TAG_COMPRESSION
#define TAG_COMPRESSION 0x0103
Definition at line 267 of file exif.c.
TAG_COPYRIGHT
#define TAG_COPYRIGHT 0x8298
Definition at line 285 of file exif.c.
TAG_DATETIME_ORIGINAL
#define TAG_DATETIME_ORIGINAL 0x9003
Definition at line 299 of file exif.c.
TAG_DIGIZOOM
#define TAG_DIGIZOOM 0x0204
Definition at line 279 of file exif.c.
TAG_EXIF_OFFSET
#define TAG_EXIF_OFFSET 0x8769
Definition at line 264 of file exif.c.
TAG_EXIFVERSION
#define TAG_EXIFVERSION 0x9000
Definition at line 292 of file exif.c.
TAG_EXPOSURETIME
#define TAG_EXPOSURETIME 0x829A
Definition at line 287 of file exif.c.
TAG_FLASH
#define TAG_FLASH 0x9209
Definition at line 304 of file exif.c.
TAG_FNUMBER
#define TAG_FNUMBER 0x829D
Definition at line 288 of file exif.c.
TAG_FOCALLENGTH
#define TAG_FOCALLENGTH 0x920A
Definition at line 297 of file exif.c.
TAG_FOCALPLANEUNITS
#define TAG_FOCALPLANEUNITS 0xa210
Definition at line 307 of file exif.c.
TAG_FOCALPLANEXRES
#define TAG_FOCALPLANEXRES 0xa20E
Definition at line 306 of file exif.c.
TAG_GPSINFO
#define TAG_GPSINFO 0x8825
Definition at line 290 of file exif.c.
TAG_IMAGEWIDTH
#define TAG_IMAGEWIDTH 0xA002
Definition at line 308 of file exif.c.
TAG_INTEROP_OFFSET
#define TAG_INTEROP_OFFSET 0xa005
Definition at line 265 of file exif.c.
TAG_ISOSPEED
#define TAG_ISOSPEED 0x8827
Definition at line 291 of file exif.c.
TAG_JPEGQUAL
#define TAG_JPEGQUAL 0x0201
Definition at line 277 of file exif.c.
TAG_LIGHT_SOURCE
#define TAG_LIGHT_SOURCE 0x9208
Definition at line 303 of file exif.c.
TAG_MACRO
#define TAG_MACRO 0x0202
Definition at line 278 of file exif.c.
TAG_MAKE
#define TAG_MAKE 0x010F
Definition at line 269 of file exif.c.
TAG_MAXAPERTURE
#define TAG_MAXAPERTURE 0x9205
Definition at line 296 of file exif.c.
TAG_MODEL
#define TAG_MODEL 0x0110
Definition at line 270 of file exif.c.
TAG_ORIENTATION
#define TAG_ORIENTATION 0x0112
Definition at line 271 of file exif.c.
TAG_PICTINFO
#define TAG_PICTINFO 0x0208
Definition at line 281 of file exif.c.
TAG_SHUTTERSPEED
#define TAG_SHUTTERSPEED 0x9201
Definition at line 294 of file exif.c.
TAG_SOFTWARE
#define TAG_SOFTWARE 0x0131
Definition at line 273 of file exif.c.
TAG_SOFTWARERELEASE
#define TAG_SOFTWARERELEASE 0x0207
Definition at line 280 of file exif.c.
TAG_SPECIALMODE
#define TAG_SPECIALMODE 0x0200
Definition at line 276 of file exif.c.
TAG_SUBJECT_DISTANCE
#define TAG_SUBJECT_DISTANCE 0x9206
Definition at line 302 of file exif.c.
TAG_USERCOMMENT
#define TAG_USERCOMMENT 0x9286
Definition at line 300 of file exif.c.
TRUE
#define TRUE 1
Definition at line 41 of file exif.c.
Typedef Documentation
uchar
typedef unsigned char uchar
Definition at line 38 of file exif.c.
Function Documentation
ConvertAnyFormat()
static double ConvertAnyFormat (void * ValuePtr, int Format, int MotorolaOrder) static
Definition at line 352 of file exif.c.
References EXIF_FMT_BYTE, EXIF_FMT_DOUBLE, EXIF_FMT_SBYTE, EXIF_FMT_SINGLE, EXIF_FMT_SLONG, EXIF_FMT_SRATIONAL, EXIF_FMT_SSHORT, EXIF_FMT_ULONG, EXIF_FMT_URATIONAL, EXIF_FMT_USHORT, Get16u(), Get32s(), and Get32u().
Referenced by ProcessFocalPlaneUnits().
ConvertAnyFormat2()
static char ConvertAnyFormat2 (void * ValuePtr, int ByteCount, int Format, int MotorolaOrder, exif_rec_data_t * data_p) static
Definition at line 390 of file exif.c.
References exif_rational::denom, EXIF_FMT_BYTE, EXIF_FMT_DOUBLE, EXIF_FMT_SBYTE, EXIF_FMT_SINGLE, EXIF_FMT_SLONG, EXIF_FMT_SRATIONAL, EXIF_FMT_SSHORT, EXIF_FMT_STRING, EXIF_FMT_ULONG, EXIF_FMT_URATIONAL, EXIF_FMT_USHORT, exif_strndup(), exif_rec_data_t::f, exif_rec_data_t::g, Get16u(), Get32s(), Get32u(), exif_rec_data_t::l, exif_rational::num, exif_rec_data_t::r, and exif_rec_data_t::s.
Referenced by ProcessAperture(), ProcessExifDir(), and ProcessShutterSpeed().
DiscardData()
static void DiscardData (Section_t * Sections, int * SectionsRead) static
Definition at line 1131 of file exif.c.
References Section_t::Data.
Referenced by read_jpeg_exif().
exif_alloc()
struct exif_data* exif_alloc (void)
Definition at line 71 of file exif.c.
Referenced by ReadJpegFile().
exif_append_data()
static int exif_append_data (exif_data_t ** d_p, char * name, char rec_type, int exif_format, exif_rec_data_t * data) static
Definition at line 137 of file exif.c.
References EXIF_ALLOC_SIZE, EXIT_FAILURE, EXIT_SUCCESS, exif_data::n_alloc, exif_data::n_recs, name, exif_record::rec_data, exif_record::rec_name, exif_record::rec_type, and exif_data::recs.
Referenced by process_COM(), process_SOFn(), ProcessAperture(), ProcessExifDir(), ProcessFocalPlaneUnits(), ProcessShutterSpeed(), ProcessUserComment(), and ProcessVersion().
exif_error()
static void exif_error (char * fmt, ...) static
Definition at line 81 of file exif.c.
References fmt.
Referenced by process_EXIF(), ProcessExifDir(), ReadJpegFile(), and scan_JPEG_header().
exif_find_record()
exif_record_t* exif_find_record (exif_data_t * d, const char * rec_name)
Definition at line 1272 of file exif.c.
References exif_data::n_recs, exif_record::rec_name, and exif_data::recs.
Referenced by ProcessAperture(), and ProcessMakerNote().
exif_free_data()
void exif_free_data (struct exif_data * d)
Definition at line 1240 of file exif.c.
References exif_data::n_recs, exif_record::rec_data, exif_record::rec_name, exif_record::rec_type, exif_data::recs, and exif_rec_data_t::s.
exif_init()
void exif_init (void *(*)(int) malloc_fn, void(*)(void *) free_fn, void *(*)(void *, int) realloc_fn)
Definition at line 1253 of file exif.c.
References exif_free_fn, exif_malloc_fn, and exif_realloc_fn.
exif_parse_fd()
exif_data_t* exif_parse_fd (int fd)
Definition at line 1210 of file exif.c.
References ImageInfoType::d, ImageInfoType::filename, read_jpeg_exif(), and TRUE.
exif_parse_file()
exif_data_t* exif_parse_file (const char * filename)
Definition at line 1222 of file exif.c.
References ImageInfoType::d, ImageInfoType::filename, read_jpeg_exif(), and TRUE.
exif_strndup()
static char* exif_strndup (char * str, int len) static
Definition at line 62 of file exif.c.
Referenced by ConvertAnyFormat2(), ProcessUserComment(), and ProcessVersion().
Get16m()
static int Get16m (void * Short) static
Definition at line 165 of file exif.c.
Referenced by process_SOFn().
Get16u()
static int Get16u (void * Short, int MotorolaOrder) static
Definition at line 320 of file exif.c.
Referenced by ConvertAnyFormat(), ConvertAnyFormat2(), process_EXIF(), and ProcessExifDir().
Get32s()
static int Get32s (void * Long, int MotorolaOrder) static
Definition at line 331 of file exif.c.
Referenced by ConvertAnyFormat(), ConvertAnyFormat2(), and Get32u().
Get32u()
static unsigned Get32u (void * Long, int MotorolaOrder) static
Definition at line 344 of file exif.c.
References Get32s().
Referenced by ConvertAnyFormat(), ConvertAnyFormat2(), process_EXIF(), and ProcessExifDir().
process_COM()
static void process_COM (ImageInfoType * ImageInfo, uchar * Data, int length) static
Definition at line 177 of file exif.c.
References ImageInfoType::d, exif_append_data(), EXIF_FMT_COMPUTED, and exif_rec_data_t::s.
Referenced by scan_JPEG_header().
process_EXIF()
static int process_EXIF (ImageInfoType * ImageInfo, char * CharBuf, unsigned int length, char * LastExifRefd) static
Definition at line 930 of file exif.c.
References exif_error(), ExifHeader, FALSE, Get16u(), Get32u(), ImageInfoType::MotorolaOrder, ProcessExifDir(), and TRUE.
Referenced by scan_JPEG_header().
process_SOFn()
static void process_SOFn (ImageInfoType * ImageInfo, uchar * Data, int marker) static
Definition at line 208 of file exif.c.
References ImageInfoType::d, exif_append_data(), EXIF_FMT_COMPUTED, Get16m(), exif_rec_data_t::l, M_SOF0, M_SOF1, M_SOF10, M_SOF11, M_SOF13, M_SOF14, M_SOF15, M_SOF2, M_SOF3, M_SOF5, M_SOF6, M_SOF7, and M_SOF9.
Referenced by scan_JPEG_header().
ProcessAperture()
static void ProcessAperture (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p) static
Definition at line 606 of file exif.c.
References ConvertAnyFormat2(), ImageInfoType::d, exif_rational::denom, ExifTag::Desc, exif_append_data(), exif_find_record(), EXIF_FMT_COMPUTED, ImageInfoType::MotorolaOrder, exif_rational::num, exif_rec_data_t::r, and exif_rec_data_t::s.
ProcessCanonMakerNote()
static void ProcessCanonMakerNote (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p, char * OffsetBase) static
Definition at line 640 of file exif.c.
ProcessExifDir()
static int ProcessExifDir (ImageInfoType * ImageInfo, char * DirStart, char * OffsetBase, unsigned ExifLength, char * LastExifRefd) static
Definition at line 819 of file exif.c.
References ConvertAnyFormat2(), ImageInfoType::d, ExifTag::Desc, exif_append_data(), exif_error(), ExifBytesPerFormat, FALSE, ExifTag::Func, Get16u(), Get32u(), ImageInfoType::MotorolaOrder, NUM_FORMATS, ExifTag::Tag, TAG_EXIF_OFFSET, TAG_INTEROP_OFFSET, TagTable, and TRUE.
Referenced by process_EXIF().
ProcessFocalPlaneUnits()
static void ProcessFocalPlaneUnits (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p) static
Definition at line 470 of file exif.c.
References ConvertAnyFormat(), ImageInfoType::d, exif_append_data(), exif_rec_data_t::f, and ImageInfoType::MotorolaOrder.
ProcessMakerNote()
static void ProcessMakerNote (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p, char * OffsetBase) static
Definition at line 699 of file exif.c.
References ImageInfoType::d, exif_find_record(), MakerNote::Func, MakerNote::Make, MakerProcessors, exif_record::rec_data, and exif_rec_data_t::s.
ProcessShutterSpeed()
static void ProcessShutterSpeed (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p) static
Definition at line 574 of file exif.c.
References ConvertAnyFormat2(), ImageInfoType::d, exif_rational::denom, ExifTag::Desc, exif_append_data(), EXIF_FMT_COMPUTED, ImageInfoType::MotorolaOrder, exif_rational::num, and exif_rec_data_t::r.
ProcessUserComment()
static void ProcessUserComment (ImageInfoType * ImageInfo, void * _ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p) static
Definition at line 526 of file exif.c.
References ImageInfoType::d, exif_append_data(), exif_strndup(), and exif_rec_data_t::s.
ProcessVersion()
static void ProcessVersion (ImageInfoType * ImageInfo, void * ValuePtr, int ByteCount, int Format, struct ExifTag * tag_p) static
Definition at line 510 of file exif.c.
References ImageInfoType::d, ExifTag::Desc, exif_append_data(), exif_strndup(), and exif_rec_data_t::s.
read_jpeg_exif()
static int read_jpeg_exif (ImageInfoType * ImageInfo, int fd, int ReadAll) static
Definition at line 1177 of file exif.c.
References Section_t::Data, DiscardData(), FALSE, M_EXIF, ReadJpegFile(), Section_t::Size, ImageInfoType::Thumbnail, and ImageInfoType::ThumbnailSize.
Referenced by exif_parse_fd(), and exif_parse_file().
ReadJpegFile()
static int ReadJpegFile (ImageInfoType * ImageInfo, Section_t * Sections, int * SectionsRead, int fd, int ReadAll, char * LastExifRefd) static
Definition at line 1144 of file exif.c.
References ImageInfoType::d, exif_alloc(), exif_error(), FALSE, ImageInfoType::filename, and scan_JPEG_header().
Referenced by read_jpeg_exif().
scan_JPEG_header()
static int scan_JPEG_header (ImageInfoType * ImageInfo, FILE * infile, Section_t * Sections, int * SectionsRead, int ReadAll, char * LastExifRefd) static
Definition at line 971 of file exif.c.
References Section_t::Data, exif_error(), exif_malloc_fn, FALSE, M_COM, M_EOI, M_EXIF, M_SOF0, M_SOF1, M_SOF10, M_SOF11, M_SOF13, M_SOF14, M_SOF15, M_SOF2, M_SOF3, M_SOF5, M_SOF6, M_SOF7, M_SOF9, M_SOI, M_SOS, process_COM(), process_EXIF(), process_SOFn(), PSEUDO_IMAGE_MARKER, size, Section_t::Size, TRUE, and Section_t::Type.
Referenced by ReadJpegFile().
Variable Documentation
exif_free_fn
void(* exif_free_fn) (void *) (void *)
Definition at line 59 of file exif.c.
Referenced by exif_init().
exif_malloc_fn
void*(* exif_malloc_fn) (int) (int)
Definition at line 57 of file exif.c.
Referenced by exif_init(), and scan_JPEG_header().
exif_realloc_fn
void*(* exif_realloc_fn) (void *, int) (void * , int)
Definition at line 58 of file exif.c.
Referenced by exif_init().
ExifBytesPerFormat
int ExifBytesPerFormat[] = {0,1,1,2,4,8,1,1,2,4,8,4,8} static
Definition at line 257 of file exif.c.
Referenced by ProcessExifDir().
MakerProcessors
struct MakerNote MakerProcessors[] static
Initial value:
= {
        {"Canon", ProcessCanonMakerNote},
    {NULL, NULL}
}
Definition at line 640 of file exif.c.
Referenced by ProcessMakerNote().
TagTable
struct ExifTag TagTable[] static
Definition at line 699 of file exif.c.
Referenced by ProcessExifDir().