EXIF library (libexif) Internals: libexif/exif-loader.h File Reference
exif-loader.h File Reference
Defines the ExifLoader type.
#include <libexif/exif-data.h>
#include <libexif/exif-loader.h>
#include <libexif/exif-log.h>
#include <libexif/exif-mem.h>
Typedefs
typedef struct _ExifLoader ExifLoader
Functions
ExifLoader * exif_loader_new (void)
ExifLoader * exif_loader_new_mem (ExifMem *mem)
void exif_loader_ref (ExifLoader *loader)
void exif_loader_unref (ExifLoader *loader)
void exif_loader_write_file (ExifLoader *loader, const char *fname)
unsigned char exif_loader_write (ExifLoader *loader, unsigned char *buf, unsigned int sz)
void exif_loader_reset (ExifLoader *loader)
ExifData * exif_loader_get_data (ExifLoader *loader)
void exif_loader_log (ExifLoader *, ExifLog *)
Detailed Description
Defines the ExifLoader type.
Definition in file exif-loader.h.
Typedef Documentation
ExifLoader
typedef struct _ExifLoader ExifLoader
Definition at line 1 of file exif-loader.h.
Function Documentation
exif_loader_get_data()
ExifData* exif_loader_get_data (ExifLoader * loader)
Get an ExifData out of an ExifLoader
Parameters
[in] loader the loader
Returns
and allocated ExifData
Definition at line 378 of file exif-loader.c.
References _ExifLoader::buf, _ExifLoader::bytes_read, exif_data_load_data(), exif_data_log(), exif_data_new_mem(), _ExifLoader::log, and _ExifLoader::mem.
Referenced by exif_data_new_from_file().
exif_loader_log()
void exif_loader_log (ExifLoader * loader, ExifLog * log)
Definition at line 393 of file exif-loader.c.
References exif_log_ref(), exif_log_unref(), and _ExifLoader::log.
exif_loader_new()
ExifLoader* exif_loader_new (void)
Allocate a new ExifLoader
Returns
the allocated ExifLoader
Definition at line 305 of file exif-loader.c.
References exif_loader_new_mem(), exif_mem_new_default(), and exif_mem_unref().
Referenced by exif_data_new_from_file().
exif_loader_new_mem()
ExifLoader* exif_loader_new_mem (ExifMem * mem)
Allocate a new ExifLoader using an ExifMem
Parameters
[in] mem the ExifMem
Returns
the allocated ExifLoader
Definition at line 316 of file exif-loader.c.
References exif_mem_alloc(), exif_mem_ref(), _ExifLoader::mem, and _ExifLoader::ref_count.
Referenced by exif_loader_new().
exif_loader_ref()
void exif_loader_ref (ExifLoader * loader)
Increase the refcount of the ExifLoader
Parameters
[in] loader the ExifLoader to increase the refcount of.
Definition at line 335 of file exif-loader.c.
References _ExifLoader::ref_count.
exif_loader_reset()
void exif_loader_reset (ExifLoader * loader)
Reset the ExifLoader
Parameters
[in] loader the loader
Definition at line 365 of file exif-loader.c.
References _ExifLoader::b_len, _ExifLoader::buf, _ExifLoader::bytes_read, _ExifLoader::data_format, EL_DATA_FORMAT_UNKNOWN, exif_mem_free(), _ExifLoader::mem, _ExifLoader::size, and _ExifLoader::state.
Referenced by exif_loader_free(), and exif_loader_write().
exif_loader_unref()
void exif_loader_unref (ExifLoader * loader)
Decrease the refcount of the ExifLoader
Parameters
[in] loader the ExifLoader to decrease the refcount of. If the refcount reaches 0, the ExifLoader is freeed.
Definition at line 356 of file exif-loader.c.
References exif_loader_free(), and _ExifLoader::ref_count.
Referenced by exif_data_new_from_file().
exif_loader_write()
unsigned char exif_loader_write (ExifLoader * loader, unsigned char * buf, unsigned int sz)
Write a buffer to the ExifLoader
Parameters
[in] loader the loader to write too
[in] buf the buffer to read from
[in] sz the size of the buffer
Returns
1 while EXIF data is read (or while there is still hope that there will be EXIF data later on), 0 otherwise.
Definition at line 147 of file exif-loader.c.
References _, _ExifLoader::b, _ExifLoader::b_len, _ExifLoader::data_format, EL_DATA_FORMAT_EXIF, EL_DATA_FORMAT_FUJI_RAW, EL_DATA_FORMAT_JPEG, EL_DATA_FORMAT_UNKNOWN, EL_EXIF_FOUND, EL_READ, EL_READ_SIZE_BYTE_00, EL_READ_SIZE_BYTE_08, EL_READ_SIZE_BYTE_16, EL_READ_SIZE_BYTE_24, EL_SKIP_BYTES, exif_loader_copy(), exif_loader_reset(), exif_log(), EXIF_LOG_CODE_CORRUPT_DATA, EXIF_LOG_CODE_DEBUG, ExifHeader, JPEG_MARKER_APP0, JPEG_MARKER_APP1, JPEG_MARKER_APP13, JPEG_MARKER_APP2, JPEG_MARKER_COM, JPEG_MARKER_SOI, _ExifLoader::log, MAX, MIN, _ExifLoader::size, and _ExifLoader::state.
Referenced by exif_loader_write_file().
exif_loader_write_file()
void exif_loader_write_file (ExifLoader * loader, const char * fname)
Write a file to the ExifLoader
Parameters
[in] loader the loader
[in] fname the path to the file to read
Definition at line 101 of file exif-loader.c.
References _, exif_loader_write(), exif_log(), EXIF_LOG_CODE_NONE, _ExifLoader::log, and size.
Referenced by exif_data_new_from_file().