EXIF library (libexif) Internals: libexif/exif-format.c File Reference
exif-format.c File Reference
#include <config.h>
#include <libexif/exif-format.h>
#include <libexif/i18n.h>
#include <stdlib.h>
Functions
const char * exif_format_get_name (ExifFormat format)
unsigned char exif_format_get_size (ExifFormat format)
Variables
struct {
ExifFormat format
const char * name
unsigned char size
} ExifFormatTable []
Function Documentation
exif_format_get_name()
const char* exif_format_get_name (ExifFormat format)
Definition at line 49 of file exif-format.c.
References _, bindtextdomain, ExifFormatTable, format, and name.
Referenced by exif_entry_dump(), and exif_entry_fix().
exif_format_get_size()
unsigned char exif_format_get_size (ExifFormat format)
Definition at line 69 of file exif-format.c.
References ExifFormatTable, and format.
Referenced by exif_array_set_byte_order(), exif_data_load_data_entry(), exif_data_save_data_entry(), exif_entry_fix(), exif_entry_get_value(), exif_entry_initialize(), exif_mnote_data_canon_load(), exif_mnote_data_canon_save(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_save(), and exif_mnote_data_pentax_load().
Variable Documentation
struct { ... } ExifFormatTable[]
Initial value:
= {
        {EXIF_FORMAT_BYTE,      N_("Byte"),      1},
        {EXIF_FORMAT_ASCII,     N_("Ascii"),     1},
        {EXIF_FORMAT_SHORT,     N_("Short"),     2},
        {EXIF_FORMAT_LONG,      N_("Long"),      4},
        {EXIF_FORMAT_RATIONAL,  N_("Rational"),  8},
        {EXIF_FORMAT_SBYTE,     N_("SByte"),     1},
        {EXIF_FORMAT_SSHORT,    N_("SShort"),    2},
        {EXIF_FORMAT_SLONG,     N_("SLong"),     4},
        {EXIF_FORMAT_SRATIONAL, N_("SRational"), 8},
        {EXIF_FORMAT_FLOAT,     N_("Float"),     4},
        {EXIF_FORMAT_DOUBLE,    N_("Double"),    8},
        {EXIF_FORMAT_UNDEFINED, N_("Undefined"), 1},
        {0, NULL, 0}
}
Referenced by exif_format_get_name(), and exif_format_get_size().
format
ExifFormat format
Definition at line 29 of file exif-format.c.
Referenced by exif_entry_log(), exif_format_get_name(), exif_format_get_size(), exif_log(), and exif_logv().
name
const char* name
Definition at line 30 of file exif-format.c.
Referenced by exif_format_get_name().
size
unsigned char size
Definition at line 31 of file exif-format.c.
Referenced by exif_data_load_data_entry(), exif_data_load_data_thumbnail(), exif_data_new_from_data(), exif_loader_write_file(), and scan_JPEG_header().