EXIF library (libexif) Internals: libexif/olympus/exif-mnote-data-olympus.c File Reference
exif-mnote-data-olympus.c File Reference
#include <config.h>
#include "exif-mnote-data-olympus.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <libexif/exif-utils.h>
#include <libexif/exif-data.h>
Macros
#define DEBUG
Functions
static void exif_mnote_data_olympus_clear (ExifMnoteDataOlympus *n)
static void exif_mnote_data_olympus_free (ExifMnoteData *n)
static char * exif_mnote_data_olympus_get_value (ExifMnoteData *d, unsigned int i, char *val, unsigned int maxlen)
static void exif_mnote_data_olympus_save (ExifMnoteData *ne, unsigned char **buf, unsigned int *buf_size)
save the MnoteData from ne to buf
static void exif_mnote_data_olympus_load (ExifMnoteData *en, const unsigned char *buf, unsigned int buf_size)
static unsigned int exif_mnote_data_olympus_count (ExifMnoteData *n)
static unsigned int exif_mnote_data_olympus_get_id (ExifMnoteData *d, unsigned int n)
static const char * exif_mnote_data_olympus_get_name (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_olympus_get_title (ExifMnoteData *d, unsigned int i)
static const char * exif_mnote_data_olympus_get_description (ExifMnoteData *d, unsigned int i)
static void exif_mnote_data_olympus_set_byte_order (ExifMnoteData *d, ExifByteOrder o)
static void exif_mnote_data_olympus_set_offset (ExifMnoteData *n, unsigned int o)
ExifMnoteData * exif_mnote_data_olympus_new (ExifMem *mem)
Macro Definition Documentation
DEBUG
#define DEBUG
Definition at line 31 of file exif-mnote-data-olympus.c.
Function Documentation
exif_mnote_data_olympus_clear()
static void exif_mnote_data_olympus_clear (ExifMnoteDataOlympus * n) static
Definition at line 34 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _MnoteOlympusEntry::data, _ExifMnoteDataOlympus::entries, exif_mem_free(), and _ExifMnoteData::mem.
Referenced by exif_mnote_data_olympus_free(), and exif_mnote_data_olympus_load().
exif_mnote_data_olympus_count()
static unsigned int exif_mnote_data_olympus_count (ExifMnoteData * n) static
Definition at line 362 of file exif-mnote-data-olympus.c.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_free()
static void exif_mnote_data_olympus_free (ExifMnoteData * n) static
Definition at line 54 of file exif-mnote-data-olympus.c.
References exif_mnote_data_olympus_clear().
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_get_description()
static const char* exif_mnote_data_olympus_get_description (ExifMnoteData * d, unsigned int i) static
Definition at line 398 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _ExifMnoteDataOlympus::entries, mnote_olympus_tag_get_title(), and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_get_id()
static unsigned int exif_mnote_data_olympus_get_id (ExifMnoteData * d, unsigned int n) static
Definition at line 368 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _ExifMnoteDataOlympus::entries, and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_get_name()
static const char* exif_mnote_data_olympus_get_name (ExifMnoteData * d, unsigned int i) static
Definition at line 378 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _ExifMnoteDataOlympus::entries, mnote_olympus_tag_get_name(), and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_get_title()
static const char* exif_mnote_data_olympus_get_title (ExifMnoteData * d, unsigned int i) static
Definition at line 388 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _ExifMnoteDataOlympus::entries, mnote_olympus_tag_get_title(), and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_get_value()
static char* exif_mnote_data_olympus_get_value (ExifMnoteData * d, unsigned int i, char * val, unsigned int maxlen) static
Definition at line 62 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataOlympus::count, _ExifMnoteDataOlympus::entries, exif_log(), EXIF_LOG_CODE_DEBUG, _ExifMnoteData::log, mnote_olympus_entry_get_value(), mnote_olympus_tag_get_name(), and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_load()
static void exif_mnote_data_olympus_load (ExifMnoteData * en, const unsigned char * buf, unsigned int buf_size) static
Definition at line 194 of file exif-mnote-data-olympus.c.
References _MnoteOlympusEntry::components, _ExifMnoteDataOlympus::count, _MnoteOlympusEntry::data, _ExifMnoteDataOlympus::entries, EXIF_BYTE_ORDER_INTEL, EXIF_BYTE_ORDER_MOTOROLA, exif_format_get_size(), exif_get_long(), exif_get_short(), exif_log(), EXIF_LOG_CODE_DEBUG, exif_mem_alloc(), exif_mnote_data_olympus_clear(), _MnoteOlympusEntry::format, _ExifMnoteData::log, _ExifMnoteData::mem, MNOTE_NIKON1_TAG_BASE, mnote_olympus_tag_get_name(), nikonV1, nikonV2, _ExifMnoteDataOlympus::offset, olympusV1, olympusV2, _ExifMnoteDataOlympus::order, _MnoteOlympusEntry::order, _MnoteOlympusEntry::size, _MnoteOlympusEntry::tag, and _ExifMnoteDataOlympus::version.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_new()
ExifMnoteData* exif_mnote_data_olympus_new (ExifMem * mem)
Definition at line 432 of file exif-mnote-data-olympus.c.
References _ExifMnoteDataMethods::count, exif_mem_alloc(), exif_mnote_data_construct(), exif_mnote_data_olympus_count(), exif_mnote_data_olympus_free(), exif_mnote_data_olympus_get_description(), exif_mnote_data_olympus_get_id(), exif_mnote_data_olympus_get_name(), exif_mnote_data_olympus_get_title(), exif_mnote_data_olympus_get_value(), exif_mnote_data_olympus_load(), exif_mnote_data_olympus_save(), exif_mnote_data_olympus_set_byte_order(), exif_mnote_data_olympus_set_offset(), _ExifMnoteDataMethods::free, _ExifMnoteDataMethods::get_description, _ExifMnoteDataMethods::get_id, _ExifMnoteDataMethods::get_name, _ExifMnoteDataMethods::get_title, _ExifMnoteDataMethods::get_value, _ExifMnoteDataMethods::load, _ExifMnoteData::methods, _ExifMnoteDataMethods::save, _ExifMnoteDataMethods::set_byte_order, and _ExifMnoteDataMethods::set_offset.
Referenced by exif_data_load_data().
exif_mnote_data_olympus_save()
static void exif_mnote_data_olympus_save (ExifMnoteData * ne, unsigned char ** buf, unsigned int * buf_size) static
save the MnoteData from ne to buf
Parameters
ne extract the data from this structure
*buf write the mnoteData to this buffer (buffer will be allocated)
buf_size the size of the buffer
Definition at line 85 of file exif-mnote-data-olympus.c.
References _MnoteOlympusEntry::components, _ExifMnoteDataOlympus::count, _MnoteOlympusEntry::data, _ExifMnoteDataOlympus::entries, EXIF_BYTE_ORDER_INTEL, exif_format_get_size(), exif_mem_alloc(), exif_mem_realloc(), exif_set_long(), exif_set_short(), _MnoteOlympusEntry::format, _ExifMnoteData::mem, MNOTE_NIKON1_TAG_BASE, nikonV1, nikonV2, _ExifMnoteDataOlympus::offset, olympusV1, olympusV2, _ExifMnoteDataOlympus::order, _MnoteOlympusEntry::tag, and _ExifMnoteDataOlympus::version.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_set_byte_order()
static void exif_mnote_data_olympus_set_byte_order (ExifMnoteData * d, ExifByteOrder o) static
Definition at line 408 of file exif-mnote-data-olympus.c.
References _MnoteOlympusEntry::components, _ExifMnoteDataOlympus::count, _MnoteOlympusEntry::data, _ExifMnoteDataOlympus::entries, exif_array_set_byte_order(), _MnoteOlympusEntry::format, _ExifMnoteDataOlympus::order, and _MnoteOlympusEntry::order.
Referenced by exif_mnote_data_olympus_new().
exif_mnote_data_olympus_set_offset()
static void exif_mnote_data_olympus_set_offset (ExifMnoteData * n, unsigned int o) static
Definition at line 426 of file exif-mnote-data-olympus.c.
Referenced by exif_mnote_data_olympus_new().