EXIF library (libexif) Internals: libexif/exif-entry.h File Reference
exif-entry.h File Reference
#include <libexif/exif-content.h>
#include <libexif/exif-format.h>
#include <libexif/exif-mem.h>
Data Structures
struct _ExifEntry
Macros
#define exif_entry_get_ifd(e) ((e)?exif_content_get_ifd((e)->parent):EXIF_IFD_COUNT)
Typedefs
typedef struct _ExifEntry ExifEntry
typedef struct _ExifEntryPrivate ExifEntryPrivate
Functions
ExifEntry * exif_entry_new (void)
ExifEntry * exif_entry_new_mem (ExifMem *)
void exif_entry_ref (ExifEntry *entry)
void exif_entry_unref (ExifEntry *entry)
void exif_entry_free (ExifEntry *entry)
void exif_entry_initialize (ExifEntry *entry, ExifTag tag)
void exif_entry_fix (ExifEntry *entry)
const char * exif_entry_get_value (ExifEntry *entry, char *val, unsigned int maxlen)
void exif_entry_dump (ExifEntry *entry, unsigned int indent)
Macro Definition Documentation
exif_entry_get_ifd
#define exif_entry_get_ifd (e) ((e)?exif_content_get_ifd((e)->parent):EXIF_IFD_COUNT)
Definition at line 65 of file exif-entry.h.
Typedef Documentation
ExifEntry
typedef struct _ExifEntry ExifEntry
Definition at line 1 of file exif-entry.h.
ExifEntryPrivate
typedef struct _ExifEntryPrivate ExifEntryPrivate
Definition at line 1 of file exif-entry.h.
Function Documentation
exif_entry_dump()
void exif_entry_dump (ExifEntry * entry, unsigned int indent)
Definition at line 334 of file exif-entry.c.
References _ExifEntry::components, exif_entry_get_value(), exif_format_get_name(), exif_tag_get_name(), _ExifEntry::format, _ExifEntry::size, and _ExifEntry::tag.
Referenced by exif_content_dump().
exif_entry_fix()
void exif_entry_fix (ExifEntry * entry)
Definition at line 156 of file exif-entry.c.
References _, _ExifEntry::components, _ExifEntry::data, ExifRational::denominator, ExifSRational::denominator, exif_data_get_byte_order(), exif_entry_log(), exif_entry_realloc(), exif_format_get_name(), exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_srational(), EXIF_LOG_CODE_DEBUG, exif_set_rational(), exif_set_short(), EXIF_TAG_APERTURE_VALUE, EXIF_TAG_COLOR_SPACE, EXIF_TAG_CONTRAST, EXIF_TAG_CUSTOM_RENDERED, EXIF_TAG_EXPOSURE_MODE, EXIF_TAG_EXPOSURE_TIME, EXIF_TAG_FNUMBER, EXIF_TAG_FOCAL_LENGTH, EXIF_TAG_GAIN_CONTROL, exif_tag_get_name(), EXIF_TAG_ORIENTATION, EXIF_TAG_PHOTOMETRIC_INTERPRETATION, EXIF_TAG_PLANAR_CONFIGURATION, EXIF_TAG_SATURATION, EXIF_TAG_SCENE_CAPTURE_TYPE, EXIF_TAG_SENSING_METHOD, EXIF_TAG_SHARPNESS, EXIF_TAG_SUBJECT_AREA, EXIF_TAG_USER_COMMENT, EXIF_TAG_WHITE_BALANCE, EXIF_TAG_YCBCR_POSITIONING, EXIF_TAG_YCBCR_SUB_SAMPLING, _ExifEntry::format, ExifRational::numerator, ExifSRational::numerator, _ExifContent::parent, _ExifEntry::parent, _ExifEntry::priv, _ExifEntry::size, and _ExifEntry::tag.
Referenced by fix_func().
exif_entry_free()
void exif_entry_free (ExifEntry * entry)
Definition at line 141 of file exif-entry.c.
References _ExifEntry::data, exif_mem_free(), exif_mem_unref(), _ExifEntryPrivate::mem, and _ExifEntry::priv.
Referenced by exif_entry_unref().
exif_entry_get_value()
const char* exif_entry_get_value (ExifEntry * entry, char * val, unsigned int maxlen)
Definition at line 542 of file exif-entry.c.
References _, bindtextdomain, CC, CF, _ExifEntry::components, _ExifEntry::data, ExifRational::denominator, ExifSRational::denominator, elem, exif_content_get_entry(), exif_data_get_byte_order(), exif_entry_log(), EXIF_FORMAT_ASCII, EXIF_FORMAT_BYTE, EXIF_FORMAT_DOUBLE, EXIF_FORMAT_FLOAT, exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SBYTE, EXIF_FORMAT_SHORT, EXIF_FORMAT_SLONG, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), exif_get_slong(), exif_get_srational(), EXIF_IFD_0, EXIF_LOG_CODE_DEBUG, EXIF_TAG_APERTURE_VALUE, EXIF_TAG_BRIGHTNESS_VALUE, EXIF_TAG_COLOR_SPACE, EXIF_TAG_COMPONENTS_CONFIGURATION, EXIF_TAG_COMPRESSION, EXIF_TAG_CONTRAST, EXIF_TAG_COPYRIGHT, EXIF_TAG_CUSTOM_RENDERED, EXIF_TAG_EXIF_VERSION, EXIF_TAG_EXPOSURE_BIAS_VALUE, EXIF_TAG_EXPOSURE_MODE, EXIF_TAG_EXPOSURE_PROGRAM, EXIF_TAG_EXPOSURE_TIME, EXIF_TAG_FILE_SOURCE, EXIF_TAG_FLASH, EXIF_TAG_FLASH_PIX_VERSION, EXIF_TAG_FNUMBER, EXIF_TAG_FOCAL_LENGTH, EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT, EXIF_TAG_GAIN_CONTROL, EXIF_TAG_INTEROPERABILITY_VERSION, EXIF_TAG_MAKE, EXIF_TAG_MAKER_NOTE, EXIF_TAG_MAX_APERTURE_VALUE, EXIF_TAG_METERING_MODE, EXIF_TAG_MODEL, EXIF_TAG_ORIENTATION, EXIF_TAG_PHOTOMETRIC_INTERPRETATION, EXIF_TAG_PLANAR_CONFIGURATION, EXIF_TAG_RESOLUTION_UNIT, EXIF_TAG_SATURATION, EXIF_TAG_SCENE_CAPTURE_TYPE, EXIF_TAG_SENSING_METHOD, EXIF_TAG_SHARPNESS, EXIF_TAG_SHUTTER_SPEED_VALUE, EXIF_TAG_SUBJECT_AREA, EXIF_TAG_SUBJECT_DISTANCE, EXIF_TAG_SUBJECT_DISTANCE_RANGE, EXIF_TAG_USER_COMMENT, EXIF_TAG_WHITE_BALANCE, EXIF_TAG_YCBCR_POSITIONING, EXIF_TAG_YCBCR_SUB_SAMPLING, _ExifEntry::format, _ExifData::ifd, index, list, list2, MIN, ExifRational::numerator, ExifSRational::numerator, _ExifContent::parent, _ExifEntry::parent, _ExifEntry::size, strings, tag, _ExifEntry::tag, and values.
Referenced by exif_data_get_type_maker_note(), and exif_entry_dump().
exif_entry_initialize()
void exif_entry_initialize (ExifEntry * entry, ExifTag tag)
Definition at line 1089 of file exif-entry.c.
References _, _ExifEntry::components, _ExifEntry::data, ExifRational::denominator, exif_data_get_byte_order(), exif_entry_alloc(), EXIF_FORMAT_ASCII, exif_format_get_size(), EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SRATIONAL, EXIF_FORMAT_UNDEFINED, exif_set_rational(), exif_set_short(), EXIF_TAG_APERTURE_VALUE, EXIF_TAG_ARTIST, EXIF_TAG_BITS_PER_SAMPLE, EXIF_TAG_BRIGHTNESS_VALUE, EXIF_TAG_COMPRESSED_BITS_PER_PIXEL, EXIF_TAG_COMPRESSION, EXIF_TAG_CONTRAST, EXIF_TAG_COPYRIGHT, EXIF_TAG_CUSTOM_RENDERED, EXIF_TAG_DATE_TIME, EXIF_TAG_DATE_TIME_DIGITIZED, EXIF_TAG_DATE_TIME_ORIGINAL, EXIF_TAG_DIGITAL_ZOOM_RATIO, EXIF_TAG_EXIF_IFD_POINTER, EXIF_TAG_EXIF_VERSION, EXIF_TAG_EXPOSURE_BIAS_VALUE, EXIF_TAG_EXPOSURE_INDEX, EXIF_TAG_EXPOSURE_MODE, EXIF_TAG_EXPOSURE_PROGRAM, EXIF_TAG_EXPOSURE_TIME, EXIF_TAG_FILE_SOURCE, EXIF_TAG_FLASH_ENERGY, EXIF_TAG_FLASH_PIX_VERSION, EXIF_TAG_FNUMBER, EXIF_TAG_FOCAL_LENGTH, EXIF_TAG_FOCAL_LENGTH_IN_35MM_FILM, EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT, EXIF_TAG_FOCAL_PLANE_X_RESOLUTION, EXIF_TAG_FOCAL_PLANE_Y_RESOLUTION, EXIF_TAG_GAIN_CONTROL, EXIF_TAG_GPS_INFO_IFD_POINTER, EXIF_TAG_IMAGE_DESCRIPTION, EXIF_TAG_IMAGE_LENGTH, EXIF_TAG_IMAGE_WIDTH, EXIF_TAG_INTEROPERABILITY_IFD_POINTER, EXIF_TAG_JPEG_INTERCHANGE_FORMAT, EXIF_TAG_JPEG_INTERCHANGE_FORMAT_LENGTH, EXIF_TAG_LIGHT_SOURCE, EXIF_TAG_MAKE, EXIF_TAG_MAKER_NOTE, EXIF_TAG_MAX_APERTURE_VALUE, EXIF_TAG_METERING_MODE, EXIF_TAG_MODEL, EXIF_TAG_ORIENTATION, EXIF_TAG_PHOTOMETRIC_INTERPRETATION, EXIF_TAG_PIXEL_X_DIMENSION, EXIF_TAG_PIXEL_Y_DIMENSION, EXIF_TAG_PLANAR_CONFIGURATION, EXIF_TAG_PRIMARY_CHROMATICITIES, EXIF_TAG_REFERENCE_BLACK_WHITE, EXIF_TAG_RESOLUTION_UNIT, EXIF_TAG_SAMPLES_PER_PIXEL, EXIF_TAG_SATURATION, EXIF_TAG_SCENE_CAPTURE_TYPE, EXIF_TAG_SCENE_TYPE, EXIF_TAG_SENSING_METHOD, EXIF_TAG_SHARPNESS, EXIF_TAG_SHUTTER_SPEED_VALUE, EXIF_TAG_SOFTWARE, EXIF_TAG_SUB_SEC_TIME, EXIF_TAG_SUB_SEC_TIME_DIGITIZED, EXIF_TAG_SUB_SEC_TIME_ORIGINAL, EXIF_TAG_SUBJECT_DISTANCE, EXIF_TAG_SUBJECT_DISTANCE_RANGE, EXIF_TAG_SUBJECT_LOCATION, EXIF_TAG_USER_COMMENT, EXIF_TAG_WHITE_BALANCE, EXIF_TAG_WHITE_POINT, EXIF_TAG_X_RESOLUTION, EXIF_TAG_Y_RESOLUTION, EXIF_TAG_YCBCR_POSITIONING, EXIF_TAG_YCBCR_SUB_SAMPLING, _ExifEntry::format, ExifRational::numerator, _ExifContent::parent, _ExifEntry::parent, _ExifEntry::size, tag, and _ExifEntry::tag.
Referenced by exif_content_fix().
exif_entry_new()
ExifEntry* exif_entry_new (void)
Definition at line 95 of file exif-entry.c.
References exif_entry_new_mem(), exif_mem_new_default(), and exif_mem_unref().
Referenced by exif_content_fix().
exif_entry_new_mem()
ExifEntry* exif_entry_new_mem (ExifMem * mem)
Definition at line 106 of file exif-entry.c.
References exif_mem_alloc(), exif_mem_free(), exif_mem_ref(), _ExifEntryPrivate::mem, _ExifEntry::priv, and _ExifEntryPrivate::ref_count.
Referenced by exif_data_load_data_content(), and exif_entry_new().
exif_entry_ref()
void exif_entry_ref (ExifEntry * entry)
Definition at line 123 of file exif-entry.c.
References _ExifEntry::priv, and _ExifEntryPrivate::ref_count.
Referenced by exif_content_add_entry().
exif_entry_unref()
void exif_entry_unref (ExifEntry * entry)
Definition at line 131 of file exif-entry.c.
References exif_entry_free(), _ExifEntry::priv, and _ExifEntryPrivate::ref_count.
Referenced by exif_content_fix(), exif_content_free(), exif_content_remove_entry(), and exif_data_load_data_content().