EXIF library (libexif) Internals: libexif/olympus/mnote-olympus-tag.h File Reference
mnote-olympus-tag.h File Reference
Typedefs
typedef enum _MnoteOlympusTag MnoteOlympusTag
Enumerations
enum _MnoteOlympusTag {
MNOTE_NIKON_TAG_FIRMWARE = 0x0001 , MNOTE_NIKON_TAG_ISO = 0x0002 , MNOTE_NIKON_TAG_COLORMODE1 = 0x0003 , MNOTE_NIKON_TAG_QUALITY = 0x0004 ,
MNOTE_NIKON_TAG_WHITEBALANCE = 0x0005 , MNOTE_NIKON_TAG_SHARPENING = 0x0006 , MNOTE_NIKON_TAG_FOCUSMODE = 0x0007 , MNOTE_NIKON_TAG_FLASHSETTING = 0x0008 ,
MNOTE_NIKON_TAG_FLASHMODE = 0x0009 , MNOTE_NIKON_TAG_WHITEBALANCEFINE = 0x000b , MNOTE_NIKON_TAG_WHITEBALANCERB = 0x000c , MNOTE_NIKON_TAG_UNKNOWN_0X000D = 0x000d ,
MNOTE_NIKON_TAG_EXPOSUREDIFF = 0x000e , MNOTE_NIKON_TAG_ISOSELECTION = 0x000f , MNOTE_NIKON_TAG_PREVIEWIMAGE = 0x0011 , MNOTE_NIKON_TAG_FLASHEXPCOMPENSATION = 0x0012 ,
MNOTE_NIKON_TAG_ISO2 = 0x0013 , MNOTE_NIKON_TAG_IMAGEBOUNDARY = 0x0016 , MNOTE_NIKON_TAG_UNKNOWN_0X0017 = 0x0017 , MNOTE_NIKON_TAG_FLASHEXPOSUREBRACKETVAL = 0x0018 ,
MNOTE_NIKON_TAG_EXPOSUREBRACKETVAL = 0x0019 , MNOTE_NIKON_TAG_IMAGEADJUSTMENT = 0x0080 , MNOTE_NIKON_TAG_TONECOMPENSATION = 0x0081 , MNOTE_NIKON_TAG_ADAPTER = 0x0082 ,
MNOTE_NIKON_TAG_LENSTYPE = 0x0083 , MNOTE_NIKON_TAG_LENS = 0x0084 , MNOTE_NIKON_TAG_MANUALFOCUSDISTANCE = 0x0085 , MNOTE_NIKON_TAG_DIGITALZOOM = 0x0086 ,
MNOTE_NIKON_TAG_FLASHUSED = 0x0087 , MNOTE_NIKON_TAG_AFFOCUSPOSITION = 0x0088 , MNOTE_NIKON_TAG_BRACKETING = 0x0089 , MNOTE_NIKON_TAG_UNKNOWN_0X008A = 0x008a ,
MNOTE_NIKON_TAG_LENS_FSTOPS = 0x008b , MNOTE_NIKON_TAG_CURVE = 0x008c , MNOTE_NIKON_TAG_COLORMODE = 0x008d , MNOTE_NIKON_TAG_LIGHTTYPE = 0x0090 ,
MNOTE_NIKON_TAG_UNKNOWN_0X0091 = 0x0091 , MNOTE_NIKON_TAG_HUE = 0x0092 , MNOTE_NIKON_TAG_SATURATION = 0x0094 , MNOTE_NIKON_TAG_NOISEREDUCTION = 0x0095 ,
MNOTE_NIKON_TAG_UNKNOWN_0X0097 = 0x0097 , MNOTE_NIKON_TAG_UNKNOWN_0X0098 = 0x0098 , MNOTE_NIKON_TAG_SENSORPIXELSIZE = 0x009a , MNOTE_NIKON_TAG_UNKNOWN_0X009B = 0x009b ,
MNOTE_NIKON_TAG_SERIALNUMBER = 0x00a0 , MNOTE_NIKON_TAG_IMAGE_DATASIZE = 0x00a2 , MNOTE_NIKON_TAG_UNKNOWN_0X00A3 = 0x00a3 , MNOTE_NIKON_TAG_TOTALPICTURES = 0x00a7 ,
MNOTE_NIKON_TAG_UNKNOWN_0X00A8 = 0x00a8 , MNOTE_NIKON_TAG_OPTIMIZATION = 0x00a9 , MNOTE_NIKON_TAG_SATURATION2 = 0x00aa , MNOTE_NIKON_TAG_VARIPROGRAM = 0x00ab ,
MNOTE_NIKON_TAG_CAPTUREEDITORDATA = 0x0e01 , MNOTE_NIKON_TAG_CAPTUREEDITORVER = 0x0e09 , MNOTE_NIKON_TAG_UNKNOWN_0X0E0E = 0x0e0e , MNOTE_NIKON_TAG_UNKNOWN_0X0E10 = 0x0e10 ,
MNOTE_NIKON1_TAG_BASE = 0x8000 , MNOTE_NIKON1_TAG_UNKNOWN_0X0002 = 0x0002 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_QUALITY = 0x0003 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_COLORMODE = 0x0004 + MNOTE_NIKON1_TAG_BASE ,
MNOTE_NIKON1_TAG_IMAGEADJUSTMENT = 0x0005 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_CCDSENSITIVITY = 0x0006 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_WHITEBALANCE = 0x0007 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_FOCUS = 0x0008 + MNOTE_NIKON1_TAG_BASE ,
MNOTE_NIKON1_TAG_UNKNOWN_0X0009 = 0x0009 + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_DIGITALZOOM = 0x000a + MNOTE_NIKON1_TAG_BASE , MNOTE_NIKON1_TAG_CONVERTER = 0x000b + MNOTE_NIKON1_TAG_BASE , MNOTE_OLYMPUS_TAG_MODE = 0x0200 ,
MNOTE_OLYMPUS_TAG_QUALITY = 0x0201 , MNOTE_OLYMPUS_TAG_MACRO = 0x0202 , MNOTE_OLYMPUS_TAG_UNKNOWN_1 = 0x0203 , MNOTE_OLYMPUS_TAG_DIGIZOOM = 0x0204 ,
MNOTE_OLYMPUS_TAG_UNKNOWN_2 = 0x0205 , MNOTE_OLYMPUS_TAG_UNKNOWN_3 = 0x0206 , MNOTE_OLYMPUS_TAG_VERSION = 0x0207 , MNOTE_OLYMPUS_TAG_INFO = 0x0208 ,
MNOTE_OLYMPUS_TAG_ID = 0x0209 , MNOTE_OLYMPUS_TAG_UNKNOWN_4 = 0x0f04 , MNOTE_OLYMPUS_TAG_FLASHMODE = 0x1004 , MNOTE_OLYMPUS_TAG_MANFOCUS = 0x100b ,
MNOTE_OLYMPUS_TAG_FOCUSDIST = 0x100c , MNOTE_OLYMPUS_TAG_SHARPNESS = 0x100f , MNOTE_OLYMPUS_TAG_WBALANCE = 0x1015 , MNOTE_OLYMPUS_TAG_CONTRAST = 0x1029
}
Functions
const char * mnote_olympus_tag_get_name (MnoteOlympusTag tag)
const char * mnote_olympus_tag_get_title (MnoteOlympusTag tag)
const char * mnote_olympus_tag_get_description (MnoteOlympusTag tag)
Typedef Documentation
MnoteOlympusTag
typedef enum _MnoteOlympusTag MnoteOlympusTag
Definition at line 1 of file mnote-olympus-tag.h.
Enumeration Type Documentation
_MnoteOlympusTag
enum _MnoteOlympusTag
Enumerator
MNOTE_NIKON_TAG_FIRMWARE
MNOTE_NIKON_TAG_ISO
MNOTE_NIKON_TAG_COLORMODE1
MNOTE_NIKON_TAG_QUALITY
MNOTE_NIKON_TAG_WHITEBALANCE
MNOTE_NIKON_TAG_SHARPENING
MNOTE_NIKON_TAG_FOCUSMODE
MNOTE_NIKON_TAG_FLASHSETTING
MNOTE_NIKON_TAG_FLASHMODE
MNOTE_NIKON_TAG_WHITEBALANCEFINE
MNOTE_NIKON_TAG_WHITEBALANCERB
MNOTE_NIKON_TAG_UNKNOWN_0X000D
MNOTE_NIKON_TAG_EXPOSUREDIFF
MNOTE_NIKON_TAG_ISOSELECTION
MNOTE_NIKON_TAG_PREVIEWIMAGE
MNOTE_NIKON_TAG_FLASHEXPCOMPENSATION
MNOTE_NIKON_TAG_ISO2
MNOTE_NIKON_TAG_IMAGEBOUNDARY
MNOTE_NIKON_TAG_UNKNOWN_0X0017
MNOTE_NIKON_TAG_FLASHEXPOSUREBRACKETVAL
MNOTE_NIKON_TAG_EXPOSUREBRACKETVAL
MNOTE_NIKON_TAG_IMAGEADJUSTMENT
MNOTE_NIKON_TAG_TONECOMPENSATION
MNOTE_NIKON_TAG_ADAPTER
MNOTE_NIKON_TAG_LENSTYPE
MNOTE_NIKON_TAG_LENS
MNOTE_NIKON_TAG_MANUALFOCUSDISTANCE
MNOTE_NIKON_TAG_DIGITALZOOM
MNOTE_NIKON_TAG_FLASHUSED
MNOTE_NIKON_TAG_AFFOCUSPOSITION
MNOTE_NIKON_TAG_BRACKETING
MNOTE_NIKON_TAG_UNKNOWN_0X008A
MNOTE_NIKON_TAG_LENS_FSTOPS
MNOTE_NIKON_TAG_CURVE
MNOTE_NIKON_TAG_COLORMODE
MNOTE_NIKON_TAG_LIGHTTYPE
MNOTE_NIKON_TAG_UNKNOWN_0X0091
MNOTE_NIKON_TAG_HUE
MNOTE_NIKON_TAG_SATURATION
MNOTE_NIKON_TAG_NOISEREDUCTION
MNOTE_NIKON_TAG_UNKNOWN_0X0097
MNOTE_NIKON_TAG_UNKNOWN_0X0098
MNOTE_NIKON_TAG_SENSORPIXELSIZE
MNOTE_NIKON_TAG_UNKNOWN_0X009B
MNOTE_NIKON_TAG_SERIALNUMBER
MNOTE_NIKON_TAG_IMAGE_DATASIZE
MNOTE_NIKON_TAG_UNKNOWN_0X00A3
MNOTE_NIKON_TAG_TOTALPICTURES
MNOTE_NIKON_TAG_UNKNOWN_0X00A8
MNOTE_NIKON_TAG_OPTIMIZATION
MNOTE_NIKON_TAG_SATURATION2
MNOTE_NIKON_TAG_VARIPROGRAM
MNOTE_NIKON_TAG_CAPTUREEDITORDATA
MNOTE_NIKON_TAG_CAPTUREEDITORVER
MNOTE_NIKON_TAG_UNKNOWN_0X0E0E
MNOTE_NIKON_TAG_UNKNOWN_0X0E10
MNOTE_NIKON1_TAG_BASE
MNOTE_NIKON1_TAG_UNKNOWN_0X0002
MNOTE_NIKON1_TAG_QUALITY
MNOTE_NIKON1_TAG_COLORMODE
MNOTE_NIKON1_TAG_IMAGEADJUSTMENT
MNOTE_NIKON1_TAG_CCDSENSITIVITY
MNOTE_NIKON1_TAG_WHITEBALANCE
MNOTE_NIKON1_TAG_FOCUS
MNOTE_NIKON1_TAG_UNKNOWN_0X0009
MNOTE_NIKON1_TAG_DIGITALZOOM
MNOTE_NIKON1_TAG_CONVERTER
MNOTE_OLYMPUS_TAG_MODE
MNOTE_OLYMPUS_TAG_QUALITY
MNOTE_OLYMPUS_TAG_MACRO
MNOTE_OLYMPUS_TAG_UNKNOWN_1
MNOTE_OLYMPUS_TAG_DIGIZOOM
MNOTE_OLYMPUS_TAG_UNKNOWN_2
MNOTE_OLYMPUS_TAG_UNKNOWN_3
MNOTE_OLYMPUS_TAG_VERSION
MNOTE_OLYMPUS_TAG_INFO
MNOTE_OLYMPUS_TAG_ID
MNOTE_OLYMPUS_TAG_UNKNOWN_4
MNOTE_OLYMPUS_TAG_FLASHMODE
MNOTE_OLYMPUS_TAG_MANFOCUS
MNOTE_OLYMPUS_TAG_FOCUSDIST
MNOTE_OLYMPUS_TAG_SHARPNESS
MNOTE_OLYMPUS_TAG_WBALANCE
MNOTE_OLYMPUS_TAG_CONTRAST
Definition at line 28 of file mnote-olympus-tag.h.
Function Documentation
mnote_olympus_tag_get_description()
const char* mnote_olympus_tag_get_description (MnoteOlympusTag tag)
Definition at line 147 of file mnote-olympus-tag.c.
References _, bindtextdomain, description, table, and tag.
mnote_olympus_tag_get_name()
const char* mnote_olympus_tag_get_name (MnoteOlympusTag tag)
Definition at line 126 of file mnote-olympus-tag.c.
References name, table, and tag.
Referenced by exif_mnote_data_olympus_get_name(), exif_mnote_data_olympus_get_value(), and exif_mnote_data_olympus_load().
mnote_olympus_tag_get_title()
const char* mnote_olympus_tag_get_title (MnoteOlympusTag tag)
Definition at line 136 of file mnote-olympus-tag.c.
References _, bindtextdomain, table, tag, and title.
Referenced by exif_mnote_data_olympus_get_description(), and exif_mnote_data_olympus_get_title().