EXIF library (libexif) Internals: libexif/olympus/mnote-olympus-entry.c File Reference
mnote-olympus-entry.c File Reference
#include <config.h>
#include "mnote-olympus-entry.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libexif/exif-format.h>
#include <libexif/exif-utils.h>
#include <libexif/exif-entry.h>
#include <libexif/i18n.h>
Macros
#define CF(format, target, v, maxlen)
#define CC(number, target, v, maxlen)
#define CC2(number, t1, t2, v, maxlen)
Functions
char * mnote_olympus_entry_get_value (MnoteOlympusEntry *entry, char *v, unsigned int maxlen)
Variables
struct {
ExifTag tag
ExifFormat fmt
struct {
int index
const char * string
} elem [10]
} items []
Macro Definition Documentation
CC
#define CC (number, target, v, maxlen)
Value:
{                                                                       \
        if (number != target) {                                         \
                snprintf (v, maxlen,                                    \
                        _("Invalid number of components (%i, "          \
                        "expected %i)."), (int) number, (int) target);  \
                break;                                                  \
        }                                                               \
}
Definition at line 45 of file mnote-olympus-entry.c.
CC2
#define CC2 (number, t1, t2, v, maxlen)
Value:
{                                                                       \
        if ((number < t1) || (number > t2)) {                           \
                snprintf (v, maxlen,                                    \
                        _("Invalid number of components (%i, "          \
                        "expected %i or %i)."), (int) number,           \
                        (int) t1, (int) t2);                            \
                break;                                                  \
        }                                                               \
}
Definition at line 55 of file mnote-olympus-entry.c.
CF
#define CF (format, target, v, maxlen)
Value:
{                                                               \
        if (format != target) {                                 \
                snprintf (v, maxlen,                            \
                        _("Invalid format '%s', "               \
                        "expected '%s'."),                      \
                        exif_format_get_name (format),          \
                        exif_format_get_name (target));         \
                break;                                          \
        }                                                       \
}
Definition at line 33 of file mnote-olympus-entry.c.
Function Documentation
mnote_olympus_entry_get_value()
char* mnote_olympus_entry_get_value (MnoteOlympusEntry * entry, char * v, unsigned int maxlen)
Definition at line 168 of file mnote-olympus-entry.c.
References _, CC, CC2, CF, _MnoteOlympusEntry::components, _MnoteOlympusEntry::data, ExifRational::denominator, elem, EXIF_FORMAT_ASCII, EXIF_FORMAT_BYTE, EXIF_FORMAT_LONG, EXIF_FORMAT_RATIONAL, EXIF_FORMAT_SHORT, EXIF_FORMAT_SSHORT, EXIF_FORMAT_UNDEFINED, exif_get_long(), exif_get_rational(), exif_get_short(), _MnoteOlympusEntry::format, index, items, MIN, MNOTE_NIKON1_TAG_CCDSENSITIVITY, MNOTE_NIKON1_TAG_COLORMODE, MNOTE_NIKON1_TAG_CONVERTER, MNOTE_NIKON1_TAG_DIGITALZOOM, MNOTE_NIKON1_TAG_FOCUS, MNOTE_NIKON1_TAG_IMAGEADJUSTMENT, MNOTE_NIKON1_TAG_QUALITY, MNOTE_NIKON1_TAG_WHITEBALANCE, MNOTE_NIKON_TAG_ADAPTER, MNOTE_NIKON_TAG_AFFOCUSPOSITION, MNOTE_NIKON_TAG_COLORMODE, MNOTE_NIKON_TAG_COLORMODE1, MNOTE_NIKON_TAG_DIGITALZOOM, MNOTE_NIKON_TAG_EXPOSUREDIFF, MNOTE_NIKON_TAG_FIRMWARE, MNOTE_NIKON_TAG_FLASHEXPCOMPENSATION, MNOTE_NIKON_TAG_FLASHEXPOSUREBRACKETVAL, MNOTE_NIKON_TAG_FLASHMODE, MNOTE_NIKON_TAG_FLASHSETTING, MNOTE_NIKON_TAG_FLASHUSED, MNOTE_NIKON_TAG_FOCUSMODE, MNOTE_NIKON_TAG_HUE, MNOTE_NIKON_TAG_IMAGEADJUSTMENT, MNOTE_NIKON_TAG_ISO, MNOTE_NIKON_TAG_ISO2, MNOTE_NIKON_TAG_ISOSELECTION, MNOTE_NIKON_TAG_LENS, MNOTE_NIKON_TAG_LENS_FSTOPS, MNOTE_NIKON_TAG_LENSTYPE, MNOTE_NIKON_TAG_MANUALFOCUSDISTANCE, MNOTE_NIKON_TAG_QUALITY, MNOTE_NIKON_TAG_SATURATION, MNOTE_NIKON_TAG_SATURATION2, MNOTE_NIKON_TAG_SENSORPIXELSIZE, MNOTE_NIKON_TAG_SHARPENING, MNOTE_NIKON_TAG_TOTALPICTURES, MNOTE_NIKON_TAG_WHITEBALANCE, MNOTE_NIKON_TAG_WHITEBALANCEFINE, MNOTE_NIKON_TAG_WHITEBALANCERB, MNOTE_OLYMPUS_TAG_CONTRAST, MNOTE_OLYMPUS_TAG_DIGIZOOM, MNOTE_OLYMPUS_TAG_FLASHMODE, MNOTE_OLYMPUS_TAG_FOCUSDIST, MNOTE_OLYMPUS_TAG_ID, MNOTE_OLYMPUS_TAG_INFO, MNOTE_OLYMPUS_TAG_MACRO, MNOTE_OLYMPUS_TAG_MANFOCUS, MNOTE_OLYMPUS_TAG_MODE, MNOTE_OLYMPUS_TAG_QUALITY, MNOTE_OLYMPUS_TAG_SHARPNESS, MNOTE_OLYMPUS_TAG_UNKNOWN_1, MNOTE_OLYMPUS_TAG_UNKNOWN_2, MNOTE_OLYMPUS_TAG_UNKNOWN_3, MNOTE_OLYMPUS_TAG_UNKNOWN_4, MNOTE_OLYMPUS_TAG_VERSION, MNOTE_OLYMPUS_TAG_WBALANCE, ExifRational::numerator, _MnoteOlympusEntry::order, _MnoteOlympusEntry::size, tag, and _MnoteOlympusEntry::tag.
Referenced by exif_mnote_data_olympus_get_value().
Variable Documentation
struct { ... } elem[10]
Referenced by mnote_olympus_entry_get_value().
fmt
ExifFormat fmt
Definition at line 68 of file mnote-olympus-entry.c.
Referenced by exif_error().
index
int index
Definition at line 70 of file mnote-olympus-entry.c.
Referenced by mnote_olympus_entry_get_value().
struct { ... } items[]
Referenced by mnote_olympus_entry_get_value().
string
const char* string
Definition at line 71 of file mnote-olympus-entry.c.
tag
ExifTag tag
Definition at line 67 of file mnote-olympus-entry.c.
Referenced by mnote_olympus_entry_get_value().